<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/38_KNN_logictic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression,Ridge,SGDRegressor,Lasso,ElasticNet,LogisticRegression
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error,accuracy_score,confusion_matrix,classification_report,roc_auc_score,roc_curve
from sklearn.preprocessing import StandardScaler,PolynomialFeatures,LabelEncoder
from scipy import stats
from sklearn.pipeline import Pipeline
from sklearn.datasets import make_regression, load_diabetes
import  plotly.express as px
import plotly.graph_objects as go
from sklearn.datasets import load_diabetes,make_classification,load_iris
import time
import matplotlib.animation as animation
from sklearn.svm import SVC

import random
from mlxtend.plotting import  plot_decision_regions
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/MachineLearning/main/breast_cancer.csv")

In [3]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [4]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [5]:
df.drop(columns=["Unnamed: 32","id"], inplace=True)

In [6]:
df.sample()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
293,B,11.85,17.46,75.54,432.7,0.08372,0.05642,0.02688,0.0228,0.1875,...,13.06,25.75,84.35,517.8,0.1369,0.1758,0.1316,0.0914,0.3101,0.07007

In [7]:
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [8]:
lable=LabelEncoder()
y=lable.fit_transform(y)

In [9]:
lable.classes_

array(['B', 'M'], dtype=object)

In [10]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
scale=StandardScaler()

In [13]:
X_train_tf=scale.fit_transform(X_train)
X_test_tf=scale.transform(X_test)

In [14]:
X_train.shape

(455, 30)

In [15]:
knn =KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_tf,y_train)

KNeighborsClassifier()

In [16]:
y_pred=knn.predict(X_test_tf)

In [17]:
accuracy_score(y_test,y_pred)

0.9736842105263158

In [18]:
knn.classes_

array([0, 1])

In [19]:
knn.predict_proba(X_test_tf).argmax(axis=1)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1])

In [20]:
data=np.array([[14.81,14.7,94.66,680.7,0.08472,0.05016,0.03416,0.02541,0.1659,15.61,17.58,101.7,760.2,0.1139,0.1011,0.1101,0.07955,0.2334,0.06142,1.481e+01, 1.470e+01, 9.466e+01, 6.807e+02, 8.472e-02, 5.016e-02,
        3.416e-02, 2.541e-02, 1.659e-01, 1.561e+01, 1.758e+01]])

In [21]:
data

array([[1.481e+01, 1.470e+01, 9.466e+01, 6.807e+02, 8.472e-02, 5.016e-02,
        3.416e-02, 2.541e-02, 1.659e-01, 1.561e+01, 1.758e+01, 1.017e+02,
        7.602e+02, 1.139e-01, 1.011e-01, 1.101e-01, 7.955e-02, 2.334e-01,
        6.142e-02, 1.481e+01, 1.470e+01, 9.466e+01, 6.807e+02, 8.472e-02,
        5.016e-02, 3.416e-02, 2.541e-02, 1.659e-01, 1.561e+01, 1.758e+01]])

In [22]:
knn.predict(data)

array([1])

In [23]:
probs = knn.predict_proba(data)

# Get index of max probability per row
indices = probs.argmax(axis=1)

# Map indices to actual class labels
actual_classes = lable.classes_[1]

print("Predicted class labels:", actual_classes)

Predicted class labels: M