<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/68_Optuna_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.3 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [3]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [7]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-28 07:31:40,135] A new study created in memory with name: no-name-0995af0e-5dd5-43ba-a0b8-598878dbd6e8
[I 2026-06-28 07:31:42,301] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 152, 'max_depth': 20}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-28 07:31:43,117] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 4}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-28 07:31:44,072] Trial 2 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 8}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-28 07:31:45,676] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 13}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-28 07:31:47,356] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 18}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-28 07:31:48,542] Trial 5 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 166, 'max_depth': 3}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-28 07:31:50,429] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 14}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-28 07:31:54,460] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 12}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-28 07:31:56,102] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 106, 'max_depth': 11}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-28 07:31:58,121] Trial 9 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 14}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-06-28 07:31:58,837] Trial 10 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 7}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:31:59,828] Trial 11 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 7}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:00,489] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 53, 'max_depth': 7}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:01,409] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 51, 'max_depth': 7}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:02,438] Trial 14 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 76, 'max_depth': 9}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:03,226] Trial 15 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 63, 'max_depth': 5}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:04,858] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 97, 'max_depth': 10}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:06,456] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 71, 'max_depth': 6}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:07,904] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 106, 'max_depth': 9}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:08,370] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:09,423] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 84, 'max_depth': 5}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:10,817] Trial 21 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:13,239] Trial 22 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 200, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:14,487] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 115, 'max_depth': 20}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:15,243] Trial 24 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 62, 'max_depth': 11}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:16,171] Trial 25 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 128, 'max_depth': 3}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:16,749] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 92, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:17,143] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 18}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:18,571] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 177, 'max_depth': 8}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:19,849] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 144, 'max_depth': 6}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:20,648] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 18}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:21,430] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:22,148] Trial 32 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 116, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:22,915] Trial 33 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 123, 'max_depth': 12}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:23,403] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:24,232] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 137, 'max_depth': 14}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:24,754] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 85, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:26,312] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 19}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:27,143] Trial 38 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 69, 'max_depth': 9}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:29,351] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 169, 'max_depth': 11}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:32,534] Trial 40 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 8}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:34,881] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 162, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:36,989] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 197, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:38,838] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:41,173] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 195, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:41,868] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:42,438] Trial 46 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 57, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:43,113] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 69, 'max_depth': 7}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:46,050] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 173, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-06-28 07:32:47,198] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 20}. Best is trial 10 with value: 0.7802607076350093.

In [8]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 54, 'max_depth': 7}

In [9]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Samplers in Optuna

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-28 07:34:02,456] A new study created in memory with name: no-name-ba864fa1-06cf-49d4-bb92-1998d5b7e1c2
[I 2026-06-28 07:34:03,709] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 13}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:34:05,694] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 189, 'max_depth': 14}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:34:06,603] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 16}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:34:08,823] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 180, 'max_depth': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:34:11,193] Trial 4 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 195, 'max_depth': 18}. Best is trial 4 with value: 0.7746741154562384.
[I 2026-06-28 07:34:12,106] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 15}. Best is trial 4 with value: 0.7746741154562384.
[I 2026-06-28 07:34:13,259] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 196, 'max_depth': 13}. Best is trial 4 with value: 0.7746741154562384.
[I 2026-06-28 07:34:13,844] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 95, 'max_depth': 20}. Best is trial 4 with value: 0.7746741154562384.
[I 2026-06-28 07:34:14,746] Trial 8 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 152, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-06-28 07:34:15,750] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 183, 'max_depth': 5}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-06-28 07:34:16,504] Trial 10 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 119, 'max_depth': 17}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:17,070] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 110, 'max_depth': 3}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:18,100] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 178, 'max_depth': 7}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:18,764] Trial 13 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 110, 'max_depth': 9}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:19,700] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 11}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:20,163] Trial 15 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 87, 'max_depth': 4}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-06-28 07:34:20,624] Trial 16 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 17}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-06-28 07:34:21,645] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 6}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-06-28 07:34:23,344] Trial 18 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 174, 'max_depth': 3}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-06-28 07:34:25,203] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 179, 'max_depth': 4}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-06-28 07:34:26,393] Trial 20 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 119, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:27,252] Trial 21 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 84, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:28,412] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 126, 'max_depth': 5}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:29,811] Trial 23 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 195, 'max_depth': 8}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:30,183] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 59, 'max_depth': 8}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:30,728] Trial 25 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 90, 'max_depth': 10}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:31,134] Trial 26 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 77, 'max_depth': 3}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:31,997] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 14}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:32,353] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 56, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:33,010] Trial 29 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 7}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:33,819] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 134, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:35,300] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 20}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:36,447] Trial 32 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 116, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:36,953] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 7}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:37,315] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:37,707] Trial 35 finished with value: 0.756052141527002 and parameters: {'n_estimators': 71, 'max_depth': 3}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:38,829] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 11}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:39,672] Trial 37 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 139, 'max_depth': 9}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:40,362] Trial 38 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:40,866] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:41,367] Trial 40 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 83, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:41,865] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 12}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:42,912] Trial 42 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 174, 'max_depth': 9}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:43,240] Trial 43 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 51, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:44,104] Trial 44 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 116, 'max_depth': 6}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:44,740] Trial 45 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 66, 'max_depth': 5}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:45,582] Trial 46 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:47,352] Trial 47 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 157, 'max_depth': 6}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:50,295] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 169, 'max_depth': 13}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-06-28 07:34:51,755] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 144, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350093.

In [12]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 119, 'max_depth': 18}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [14]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [15]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-06-28 07:36:54,649] A new study created in memory with name: no-name-2bee9589-0540-44b8-9b82-52138464fef2
[I 2026-06-28 07:36:55,514] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:36:57,511] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 07:36:58,527] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:00,192] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:01,518] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:02,063] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:03,382] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:04,299] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:05,246] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:06,446] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:07,675] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:08,870] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:09,982] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 07:37:10,277] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-28 07:37:11,099] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-28 07:37:11,579] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [16]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [17]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [18]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [19]:
# 1. Optimization History
plot_optimization_history(study).show()

In [20]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [21]:
# 3. Slice Plot
plot_slice(study).show()

In [22]:
# 4. Contour Plot
plot_contour(study).show()

In [23]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

Optimizing Multiple ML Models

In [24]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [25]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [26]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-06-28 08:46:42,656] A new study created in memory with name: no-name-74514eaa-1ee6-4ac2-90bf-56ba623c54b8
[I 2026-06-28 08:46:42,745] Trial 0 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 25.672770959982095, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.6871508379888268.
[I 2026-06-28 08:46:48,822] Trial 1 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 158, 'learning_rate': 0.010340638011415059, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.7541899441340781.
[I 2026-06-28 08:46:49,497] Trial 2 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 58, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.756052141527002.
[I 2026-06-28 08:46:51,921] Trial 3 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 72, 'learning_rate': 0.1784123840783384, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.756052141527002.
[I 2026-06-28 08:46:54,127] Trial 4 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 284, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-06-28 08:46:56,294] Trial 5 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 288, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-06-28 08:47:01,623] Trial 6 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 254, 'learning_rate': 0.13135958774112957, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-06-28 08:47:01,686] Trial 7 finished with value: 0.7430167597765363 and parameters: {'classifier': 'SVM', 'C': 0.12061179456766764, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-06-28 08:47:02,632] Trial 8 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 105, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:05,738] Trial 9 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 153, 'learning_rate': 0.041233998416284647, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:07,729] Trial 10 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 192, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:10,471] Trial 11 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 240, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:11,921] Trial 12 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 215, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:12,941] Trial 13 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 112, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:14,033] Trial 14 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 111, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:15,697] Trial 15 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 230, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:15,793] Trial 16 finished with value: 0.690875232774674 and parameters: {'classifier': 'SVM', 'C': 50.48805701714087, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:17,274] Trial 17 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:18,354] Trial 18 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 108, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-06-28 08:47:18,408] Trial 19 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.33945598216251904, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7839851024208566.
[I 2026-06-28 08:47:18,462] Trial 20 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12974262430367706, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,513] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16143224773670817, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,563] Trial 22 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15291870269272703, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,617] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.28178674410691407, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,671] Trial 24 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11830898516122991, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,730] Trial 25 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.9140599046796251, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,787] Trial 26 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.889641400789509, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,845] Trial 27 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10267409269663494, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,899] Trial 28 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6254128577173511, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:18,959] Trial 29 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 2.754134436624188, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,027] Trial 30 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10036041308909179, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,078] Trial 31 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2222955748717439, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,130] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.26608069583944866, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,204] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18436183848638896, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,268] Trial 34 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.40572489921046995, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:19,316] Trial 35 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1036808430606226, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:22,267] Trial 36 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 186, 'learning_rate': 0.011144190432226402, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:22,367] Trial 37 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18707121406560356, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:22,486] Trial 38 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5268562475831373, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,478] Trial 39 finished with value: 0.739292364990689 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 262, 'learning_rate': 0.0491212333528803, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,528] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19216389632139022, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,577] Trial 41 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11748985733923825, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,625] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16740945626963355, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,687] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17295213759066827, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,753] Trial 44 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3660846867409358, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:26,820] Trial 45 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.10316440673933024, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:28,019] Trial 46 finished with value: 0.7765363128491621 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 77, 'learning_rate': 0.037084582793864534, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:28,072] Trial 47 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.17069789579713462, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:28,145] Trial 48 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.2779748009372214, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:28,195] Trial 49 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14483194217420936, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,478] Trial 50 finished with value: 0.7039106145251397 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 133, 'learning_rate': 0.2675734877068144, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,510] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15197263036230607, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,541] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15903545405559955, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,586] Trial 53 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10114867136973767, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,624] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.28722186436744723, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,656] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13942312337434537, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,693] Trial 56 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.47536961166105035, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,725] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24207550705876274, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,863] Trial 58 finished with value: 0.6722532588454376 and parameters: {'classifier': 'SVM', 'C': 95.88362525671798, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,898] Trial 59 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13921589671959192, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:30,998] Trial 60 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.141031886061924, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:31,030] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1388610933615144, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:31,062] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14621467780798603, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:31,095] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23631769103077338, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:31,127] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13821672632959864, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:32,252] Trial 65 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 197, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:32,283] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12601068231043683, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:32,318] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.33539889873569206, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,034] Trial 68 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 296, 'learning_rate': 0.08321369487294566, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,065] Trial 69 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21616049784156696, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,104] Trial 70 finished with value: 0.7560521415270017 and parameters: {'classifier': 'SVM', 'C': 0.9346669295240823, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,136] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1128119316308151, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,167] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14183648922239997, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,198] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21895687646731077, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:37,228] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1314479971071083, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,253] Trial 75 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 176, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,296] Trial 76 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1285240045199389, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,391] Trial 77 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.3041952473226768, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,443] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2002104154763867, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,493] Trial 79 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10005690427354287, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-06-28 08:47:38,560] Trial 80 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 9.269024417554427, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.

In [27]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12974262430367706, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [28]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.687151,2026-06-28 08:46:42.663477,2026-06-28 08:46:42.745771,0 days 00:00:00.082294,25.672771,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.754190,2026-06-28 08:46:42.747096,2026-06-28 08:46:48.821987,0 days 00:00:06.074891,NaN,NaN,GradientBoosting,NaN,NaN,0.010341,14.0,4.0,2.0,158.0,COMPLETE
2,2,0.756052,2026-06-28 08:46:48.823947,2026-06-28 08:46:49.497490,0 days 00:00:00.673543,NaN,True,RandomForest,NaN,NaN,NaN,18.0,2.0,10.0,58.0,COMPLETE
3,3,0.750466,2026-06-28 08:46:49.499424,2026-06-28 08:46:51.921035,0 days 00:00:02.421611,NaN,NaN,GradientBoosting,NaN,NaN,0.178412,19.0,2.0,7.0,72.0,COMPLETE
4,4,0.770950,2026-06-28 08:46:51.922433,2026-06-28 08:46:54.127320,0 days 00:00:02.204887,NaN,False,RandomForest,NaN,NaN,NaN,20.0,7.0,8.0,284.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.769088,2026-06-28 08:47:42.530108,2026-06-28 08:47:42.609724,0 days 00:00:00.079616,0.121083,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.787709,2026-06-28 08:47:42.612657,2026-06-28 08:47:42.672314,0 days 00:00:00.059657,0.185303,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.711359,2026-06-28 08:47:42.676436,2026-06-28 08:47:42.731134,0 days 00:00:00.054698,0.148225,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.767225,2026-06-28 08:47:42.735815,2026-06-28 08:47:42.800283,0 days 00:00:00.064468,0.353747,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.789572,2026-06-28 08:47:42.802910,2026-06-28 08:47:42.853835,0 days 00:00:00.050925,0.118873,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [29]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 75
RandomForest        15
GradientBoosting    10
Name: count, dtype: int64

In [30]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.748231
RandomForest        0.764246
SVM                 0.775295
Name: value, dtype: float64

In [31]:
# 1. Optimization History
plot_optimization_history(study).show()

In [32]:
# 3. Slice Plot
plot_slice(study).show()

In [33]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [36]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

!pip install optuna-integration[xgboost]

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.9.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.9.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 2.3 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.9.0

[I 2026-06-28 08:49:15,180] A new study created in memory with name: no-name-0f86fbf7-60fc-4923-bbb9-1a7307f496e2

[0]	train-mlogloss:0.95547	eval-mlogloss:0.94971
[1]	train-mlogloss:0.79783	eval-mlogloss:0.78341
[2]	train-mlogloss:0.67231	eval-mlogloss:0.65247
[3]	train-mlogloss:0.57076	eval-mlogloss:0.54607
[4]	train-mlogloss:0.49039	eval-mlogloss:0.46135
[5]	train-mlogloss:0.42139	eval-mlogloss:0.38795
[6]	train-mlogloss:0.36711	eval-mlogloss:0.33293
[7]	train-mlogloss:0.32231	eval-mlogloss:0.28730
[8]	train-mlogloss:0.28560	eval-mlogloss:0.24725
[9]	train-mlogloss:0.25421	eval-mlogloss:0.21380
[10]	train-mlogloss:0.22741	eval-mlogloss:0.18724
[11]	train-mlogloss:0.20498	eval-mlogloss:0.16141
[12]	train-mlogloss:0.19386	eval-mlogloss:0.15294
[13]	train-mlogloss:0.17556	eval-mlogloss:0.13304
[14]	train-mlogloss:0.16646	eval-mlogloss:0.12469
[15]	train-mlogloss:0.15424	eval-mlogloss:0.11001
[16]	train-mlogloss:0.14399	eval-mlogloss:0.09882
[17]	train-mlogloss:0.13505	eval-mlogloss:0.09002
[18]	train-mlogloss:0.12594	eval-mlogloss:0.08295
[19]	train-mlogloss:0.11935	eval-mlogloss:0.07807
[20]	train-mlogloss:0.11396	eval-mlogloss:0.07155
[21]	train-mlogloss:0.10764	eval-mlogloss:0.06246
[22]	train-mlogloss:0.10406	eval-mlogloss:0.05876
[23]	train-mlogloss:0.09923	eval-mlogloss:0.05364
[24]	train-mlogloss:0.09842	eval-mlogloss:0.05283
[25]	train-mlogloss:0.09730	eval-mlogloss:0.05194
[26]	train-mlogloss:0.09604	eval-mlogloss:0.05239
[27]	train-mlogloss:0.09475	eval-mlogloss:0.05151
[28]	train-mlogloss:0.09327	eval-mlogloss:0.05070
[29]	train-mlogloss:0.09130	eval-mlogloss:0.04726
[30]	train-mlogloss:0.09046	eval-mlogloss:0.04712
[31]	train-mlogloss:0.08907	eval-mlogloss:0.04648
[32]	train-mlogloss:0.08777	eval-mlogloss:0.04481
[33]	train-mlogloss:0.08774	eval-mlogloss:0.04469
[34]	train-mlogloss:0.08632	eval-mlogloss:0.04325
[35]	train-mlogloss:0.08557	eval-mlogloss:0.04215
[36]	train-mlogloss:0.08424	eval-mlogloss:0.04074
[37]	train-mlogloss:0.08363	eval-mlogloss:0.04008
[38]	train-mlogloss:0.08320	eval-mlogloss:0.04071
[39]	train-mlogloss:0.08245	eval-mlogloss:0.03896
[40]	train-mlogloss:0.08156	eval-mlogloss:0.03974
[41]	train-mlogloss:0.08077	eval-mlogloss:0.04063
[42]	train-mlogloss:0.08024	eval-mlogloss:0.03919
[43]	train-mlogloss:0.07998	eval-mlogloss:0.03874
[44]	train-mlogloss:0.07969	eval-mlogloss:0.03696
[45]	train-mlogloss:0.07924	eval-mlogloss:0.03676
[46]	train-mlogloss:0.07877	eval-mlogloss:0.03685
[47]	train-mlogloss:0.07873	eval-mlogloss:0.03665
[48]	train-mlogloss:0.07866	eval-mlogloss:0.03686
[49]	train-mlogloss:0.07838	eval-mlogloss:0.03685
[50]	train-mlogloss:0.07766	eval-mlogloss:0.03538
[51]	train-mlogloss:0.07721	eval-mlogloss:0.03353

/usr/lib/python3.12/importlib/__init__.py:90: FutureWarning:

`optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.

[52]	train-mlogloss:0.07624	eval-mlogloss:0.03458
[53]	train-mlogloss:0.07625	eval-mlogloss:0.03480
[54]	train-mlogloss:0.07585	eval-mlogloss:0.03493
[55]	train-mlogloss:0.07509	eval-mlogloss:0.03393
[56]	train-mlogloss:0.07450	eval-mlogloss:0.03326
[57]	train-mlogloss:0.07402	eval-mlogloss:0.03236
[58]	train-mlogloss:0.07415	eval-mlogloss:0.03261
[59]	train-mlogloss:0.07378	eval-mlogloss:0.03258
[60]	train-mlogloss:0.07356	eval-mlogloss:0.03260
[61]	train-mlogloss:0.07370	eval-mlogloss:0.03277
[62]	train-mlogloss:0.07342	eval-mlogloss:0.03271
[63]	train-mlogloss:0.07298	eval-mlogloss:0.03202
[64]	train-mlogloss:0.07226	eval-mlogloss:0.03210
[65]	train-mlogloss:0.07236	eval-mlogloss:0.03194
[66]	train-mlogloss:0.07218	eval-mlogloss:0.03171
[67]	train-mlogloss:0.07180	eval-mlogloss:0.03126
[68]	train-mlogloss:0.07130	eval-mlogloss:0.03228
[69]	train-mlogloss:0.07097	eval-mlogloss:0.03137
[70]	train-mlogloss:0.07098	eval-mlogloss:0.03058
[71]	train-mlogloss:0.07094	eval-mlogloss:0.03023
[72]	train-mlogloss:0.07087	eval-mlogloss:0.02997
[73]	train-mlogloss:0.07092	eval-mlogloss:0.02935
[74]	train-mlogloss:0.07059	eval-mlogloss:0.02929
[75]	train-mlogloss:0.07034	eval-mlogloss:0.02970
[76]	train-mlogloss:0.07036	eval-mlogloss:0.03022
[77]	train-mlogloss:0.07009	eval-mlogloss:0.03044
[78]	train-mlogloss:0.06981	eval-mlogloss:0.03025
[79]	train-mlogloss:0.06948	eval-mlogloss:0.02960
[80]	train-mlogloss:0.06928	eval-mlogloss:0.02994
[81]	train-mlogloss:0.06923	eval-mlogloss:0.02999
[82]	train-mlogloss:0.06918	eval-mlogloss:0.03072
[83]	train-mlogloss:0.06913	eval-mlogloss:0.03115
[84]	train-mlogloss:0.06880	eval-mlogloss:0.03157
[85]	train-mlogloss:0.06864	eval-mlogloss:0.03110
[86]	train-mlogloss:0.06862	eval-mlogloss:0.03210
[87]	train-mlogloss:0.06835	eval-mlogloss:0.03121
[88]	train-mlogloss:0.06812	eval-mlogloss:0.03103
[89]	train-mlogloss:0.06787	eval-mlogloss:0.03079
[90]	train-mlogloss:0.06783	eval-mlogloss:0.03095
[91]	train-mlogloss:0.06791	eval-mlogloss:0.03131
[92]	train-mlogloss:0.06761	eval-mlogloss:0.03069
[93]	train-mlogloss:0.06745	eval-mlogloss:0.02991
[94]	train-mlogloss:0.06746	eval-mlogloss:0.02991
[95]	train-mlogloss:0.06754	eval-mlogloss:0.03026
[96]	train-mlogloss:0.06770	eval-mlogloss:0.03085
[97]	train-mlogloss:0.06770	eval-mlogloss:0.03108
[98]	train-mlogloss:0.06777	eval-mlogloss:0.03096
[99]	train-mlogloss:0.06723	eval-mlogloss:0.03107
[100]	train-mlogloss:0.06666	eval-mlogloss:0.02976
[101]	train-mlogloss:0.06648	eval-mlogloss:0.02945
[102]	train-mlogloss:0.06621	eval-mlogloss:0.02849
[103]	train-mlogloss:0.06612	eval-mlogloss:0.02843
[104]	train-mlogloss:0.06624	eval-mlogloss:0.02906
[105]	train-mlogloss:0.06580	eval-mlogloss:0.02803
[106]	train-mlogloss:0.06582	eval-mlogloss:0.02860
[107]	train-mlogloss:0.06588	eval-mlogloss:0.02777
[108]	train-mlogloss:0.06574	eval-mlogloss:0.02779
[109]	train-mlogloss:0.06562	eval-mlogloss:0.02764
[110]	train-mlogloss:0.06560	eval-mlogloss:0.02807
[111]	train-mlogloss:0.06576	eval-mlogloss:0.02915
[112]	train-mlogloss:0.06547	eval-mlogloss:0.02922
[113]	train-mlogloss:0.06548	eval-mlogloss:0.02800
[114]	train-mlogloss:0.06543	eval-mlogloss:0.02798
[115]	train-mlogloss:0.06534	eval-mlogloss:0.02847
[116]	train-mlogloss:0.06545	eval-mlogloss:0.02888
[117]	train-mlogloss:0.06532	eval-mlogloss:0.02854
[118]	train-mlogloss:0.06539	eval-mlogloss:0.02906
[119]	train-mlogloss:0.06523	eval-mlogloss:0.02884
[120]	train-mlogloss:0.06520	eval-mlogloss:0.02828
[121]	train-mlogloss:0.06534	eval-mlogloss:0.02848
[122]	train-mlogloss:0.06545	eval-mlogloss:0.02839
[123]	train-mlogloss:0.06530	eval-mlogloss:0.02810
[124]	train-mlogloss:0.06515	eval-mlogloss:0.02785
[125]	train-mlogloss:0.06478	eval-mlogloss:0.02710
[126]	train-mlogloss:0.06469	eval-mlogloss:0.02699
[127]	train-mlogloss:0.06457	eval-mlogloss:0.02696
[128]	train-mlogloss:0.06468	eval-mlogloss:0.02691
[129]	train-mlogloss:0.06452	eval-mlogloss:0.02689
[130]	train-mlogloss:0.06463	eval-mlogloss:0.02683
[131]	train-mlogloss:0.06449	eval-mlogloss:0.02620
[132]	train-mlogloss:0.06426	eval-mlogloss:0.02520
[133]	train-mlogloss:0.06427	eval-mlogloss:0.02586
[134]	train-mlogloss:0.06429	eval-mlogloss:0.02632
[135]	train-mlogloss:0.06438	eval-mlogloss:0.02610
[136]	train-mlogloss:0.06441	eval-mlogloss:0.02608
[137]	train-mlogloss:0.06443	eval-mlogloss:0.02575
[138]	train-mlogloss:0.06424	eval-mlogloss:0.02511
[139]	train-mlogloss:0.06387	eval-mlogloss:0.02558
[140]	train-mlogloss:0.06382	eval-mlogloss:0.02601
[141]	train-mlogloss:0.06377	eval-mlogloss:0.02609
[142]	train-mlogloss:0.06390	eval-mlogloss:0.02615
[143]	train-mlogloss:0.06372	eval-mlogloss:0.02598
[144]	train-mlogloss:0.06362	eval-mlogloss:0.02623
[145]	train-mlogloss:0.06367	eval-mlogloss:0.02615
[146]	train-mlogloss:0.06367	eval-mlogloss:0.02623
[147]	train-mlogloss:0.06350	eval-mlogloss:0.02575
[148]	train-mlogloss:0.06337	eval-mlogloss:0.02562
[149]	train-mlogloss:0.06307	eval-mlogloss:0.02639
[150]	train-mlogloss:0.06301	eval-mlogloss:0.02650
[151]	train-mlogloss:0.06277	eval-mlogloss:0.02700
[152]	train-mlogloss:0.06276	eval-mlogloss:0.02721
[153]	train-mlogloss:0.06277	eval-mlogloss:0.02726
[154]	train-mlogloss:0.06248	eval-mlogloss:0.02689
[155]	train-mlogloss:0.06248	eval-mlogloss:0.02620
[156]	train-mlogloss:0.06257	eval-mlogloss:0.02591
[157]	train-mlogloss:0.06245	eval-mlogloss:0.02550
[158]	train-mlogloss:0.06235	eval-mlogloss:0.02570
[159]	train-mlogloss:0.06224	eval-mlogloss:0.02568
[160]	train-mlogloss:0.06216	eval-mlogloss:0.02629
[161]	train-mlogloss:0.06213	eval-mlogloss:0.02626
[162]	train-mlogloss:0.06201	eval-mlogloss:0.02665
[163]	train-mlogloss:0.06196	eval-mlogloss:0.02696
[164]	train-mlogloss:0.06196	eval-mlogloss:0.02640
[165]	train-mlogloss:0.06193	eval-mlogloss:0.02607
[166]	train-mlogloss:0.06189	eval-mlogloss:0.02605
[167]	train-mlogloss:0.06195	eval-mlogloss:0.02579
[168]	train-mlogloss:0.06195	eval-mlogloss:0.02715

[I 2026-06-28 08:49:15,771] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.0003434360054112741, 'alpha': 1.557035917472026e-06, 'eta': 0.1568178961264044, 'gamma': 0.0025425644579019253, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6677265794176557, 'colsample_bytree': 0.541111550069141}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05582	eval-mlogloss:1.05722
[1]	train-mlogloss:1.01321	eval-mlogloss:1.00844
[2]	train-mlogloss:0.97182	eval-mlogloss:0.96712
[3]	train-mlogloss:0.91793	eval-mlogloss:0.90999
[4]	train-mlogloss:0.87899	eval-mlogloss:0.86897
[5]	train-mlogloss:0.83096	eval-mlogloss:0.81784
[6]	train-mlogloss:0.79841	eval-mlogloss:0.78277
[7]	train-mlogloss:0.76168	eval-mlogloss:0.74901
[8]	train-mlogloss:0.73466	eval-mlogloss:0.72097
[9]	train-mlogloss:0.70456	eval-mlogloss:0.69003
[10]	train-mlogloss:0.68069	eval-mlogloss:0.66740
[11]	train-mlogloss:0.65219	eval-mlogloss:0.63716
[12]	train-mlogloss:0.63434	eval-mlogloss:0.61948
[13]	train-mlogloss:0.61503	eval-mlogloss:0.59914
[14]	train-mlogloss:0.60196	eval-mlogloss:0.58460
[15]	train-mlogloss:0.57786	eval-mlogloss:0.56039
[16]	train-mlogloss:0.56191	eval-mlogloss:0.54318
[17]	train-mlogloss:0.54641	eval-mlogloss:0.52658
[18]	train-mlogloss:0.52821	eval-mlogloss:0.50697
[19]	train-mlogloss:0.51778	eval-mlogloss:0.49582
[20]	train-mlogloss:0.50214	eval-mlogloss:0.47871
[21]	train-mlogloss:0.48936	eval-mlogloss:0.46520
[22]	train-mlogloss:0.47860	eval-mlogloss:0.45551
[23]	train-mlogloss:0.46524	eval-mlogloss:0.44086
[24]	train-mlogloss:0.44755	eval-mlogloss:0.42048
[25]	train-mlogloss:0.43703	eval-mlogloss:0.40824
[26]	train-mlogloss:0.42678	eval-mlogloss:0.39704
[27]	train-mlogloss:0.42682	eval-mlogloss:0.39705
[28]	train-mlogloss:0.42464	eval-mlogloss:0.39408
[29]	train-mlogloss:0.41451	eval-mlogloss:0.38219
[30]	train-mlogloss:0.40695	eval-mlogloss:0.37409
[31]	train-mlogloss:0.39732	eval-mlogloss:0.36335
[32]	train-mlogloss:0.39680	eval-mlogloss:0.36302
[33]	train-mlogloss:0.39162	eval-mlogloss:0.35537
[34]	train-mlogloss:0.39162	eval-mlogloss:0.35532
[35]	train-mlogloss:0.38647	eval-mlogloss:0.34947
[36]	train-mlogloss:0.37789	eval-mlogloss:0.33997
[37]	train-mlogloss:0.37377	eval-mlogloss:0.33615
[38]	train-mlogloss:0.37371	eval-mlogloss:0.33621
[39]	train-mlogloss:0.36916	eval-mlogloss:0.33080
[40]	train-mlogloss:0.36846	eval-mlogloss:0.33009
[41]	train-mlogloss:0.36753	eval-mlogloss:0.32926
[42]	train-mlogloss:0.36696	eval-mlogloss:0.32777
[43]	train-mlogloss:0.36232	eval-mlogloss:0.32306
[44]	train-mlogloss:0.36176	eval-mlogloss:0.32208
[45]	train-mlogloss:0.36150	eval-mlogloss:0.32178
[46]	train-mlogloss:0.36126	eval-mlogloss:0.32127
[47]	train-mlogloss:0.36099	eval-mlogloss:0.32079
[48]	train-mlogloss:0.35701	eval-mlogloss:0.31537
[49]	train-mlogloss:0.35630	eval-mlogloss:0.31465
[50]	train-mlogloss:0.35146	eval-mlogloss:0.30837
[51]	train-mlogloss:0.34859	eval-mlogloss:0.30444
[52]	train-mlogloss:0.34861	eval-mlogloss:0.30457
[53]	train-mlogloss:0.34862	eval-mlogloss:0.30449
[54]	train-mlogloss:0.34842	eval-mlogloss:0.30413
[55]	train-mlogloss:0.34797	eval-mlogloss:0.30358
[56]	train-mlogloss:0.34764	eval-mlogloss:0.30337
[57]	train-mlogloss:0.34715	eval-mlogloss:0.30273
[58]	train-mlogloss:0.34703	eval-mlogloss:0.30256
[59]	train-mlogloss:0.34682	eval-mlogloss:0.30227
[60]	train-mlogloss:0.34678	eval-mlogloss:0.30226
[61]	train-mlogloss:0.34601	eval-mlogloss:0.30196
[62]	train-mlogloss:0.34558	eval-mlogloss:0.30183
[63]	train-mlogloss:0.34518	eval-mlogloss:0.30051
[64]	train-mlogloss:0.34469	eval-mlogloss:0.29973
[65]	train-mlogloss:0.34429	eval-mlogloss:0.29949
[66]	train-mlogloss:0.34361	eval-mlogloss:0.29904
[67]	train-mlogloss:0.34312	eval-mlogloss:0.29882
[68]	train-mlogloss:0.34308	eval-mlogloss:0.29878
[69]	train-mlogloss:0.34300	eval-mlogloss:0.29873
[70]	train-mlogloss:0.34298	eval-mlogloss:0.29869
[71]	train-mlogloss:0.34258	eval-mlogloss:0.29853
[72]	train-mlogloss:0.34234	eval-mlogloss:0.29813
[73]	train-mlogloss:0.34216	eval-mlogloss:0.29785
[74]	train-mlogloss:0.34215	eval-mlogloss:0.29788
[75]	train-mlogloss:0.34221	eval-mlogloss:0.29800
[76]	train-mlogloss:0.34137	eval-mlogloss:0.29690
[77]	train-mlogloss:0.34096	eval-mlogloss:0.29617
[78]	train-mlogloss:0.33768	eval-mlogloss:0.29197
[79]	train-mlogloss:0.33742	eval-mlogloss:0.29185
[80]	train-mlogloss:0.33711	eval-mlogloss:0.29176
[81]	train-mlogloss:0.33677	eval-mlogloss:0.29146
[82]	train-mlogloss:0.33674	eval-mlogloss:0.29153
[83]	train-mlogloss:0.33673	eval-mlogloss:0.29136
[84]	train-mlogloss:0.33318	eval-mlogloss:0.28712
[85]	train-mlogloss:0.33318	eval-mlogloss:0.28705
[86]	train-mlogloss:0.33314	eval-mlogloss:0.28708
[87]	train-mlogloss:0.33280	eval-mlogloss:0.28674
[88]	train-mlogloss:0.33234	eval-mlogloss:0.28595
[89]	train-mlogloss:0.32965	eval-mlogloss:0.28222
[90]	train-mlogloss:0.32969	eval-mlogloss:0.28219
[91]	train-mlogloss:0.32977	eval-mlogloss:0.28223
[92]	train-mlogloss:0.32966	eval-mlogloss:0.28209
[93]	train-mlogloss:0.32908	eval-mlogloss:0.28042
[94]	train-mlogloss:0.32875	eval-mlogloss:0.27953
[95]	train-mlogloss:0.32878	eval-mlogloss:0.27975
[96]	train-mlogloss:0.32848	eval-mlogloss:0.27958
[97]	train-mlogloss:0.32850	eval-mlogloss:0.27957
[98]	train-mlogloss:0.32830	eval-mlogloss:0.27925
[99]	train-mlogloss:0.32503	eval-mlogloss:0.27520
[100]	train-mlogloss:0.32456	eval-mlogloss:0.27476
[101]	train-mlogloss:0.32413	eval-mlogloss:0.27405
[102]	train-mlogloss:0.32381	eval-mlogloss:0.27369
[103]	train-mlogloss:0.32381	eval-mlogloss:0.27363
[104]	train-mlogloss:0.32366	eval-mlogloss:0.27354
[105]	train-mlogloss:0.32360	eval-mlogloss:0.27338
[106]	train-mlogloss:0.32315	eval-mlogloss:0.27330
[107]	train-mlogloss:0.32334	eval-mlogloss:0.27376
[108]	train-mlogloss:0.32309	eval-mlogloss:0.27346
[109]	train-mlogloss:0.32294	eval-mlogloss:0.27318
[110]	train-mlogloss:0.32293	eval-mlogloss:0.27326
[111]	train-mlogloss:0.32288	eval-mlogloss:0.27303
[112]	train-mlogloss:0.31962	eval-mlogloss:0.26819
[113]	train-mlogloss:0.31962	eval-mlogloss:0.26813
[114]	train-mlogloss:0.31964	eval-mlogloss:0.26825
[115]	train-mlogloss:0.31940	eval-mlogloss:0.26795
[116]	train-mlogloss:0.31941	eval-mlogloss:0.26800
[117]	train-mlogloss:0.31908	eval-mlogloss:0.26739
[118]	train-mlogloss:0.31904	eval-mlogloss:0.26725
[119]	train-mlogloss:0.31889	eval-mlogloss:0.26694
[120]	train-mlogloss:0.31799	eval-mlogloss:0.26598
[121]	train-mlogloss:0.31770	eval-mlogloss:0.26563
[122]	train-mlogloss:0.31728	eval-mlogloss:0.26558
[123]	train-mlogloss:0.31722	eval-mlogloss:0.26562
[124]	train-mlogloss:0.31465	eval-mlogloss:0.26174
[125]	train-mlogloss:0.31420	eval-mlogloss:0.26138
[126]	train-mlogloss:0.31409	eval-mlogloss:0.26155
[127]	train-mlogloss:0.31383	eval-mlogloss:0.26062
[128]	train-mlogloss:0.31347	eval-mlogloss:0.25933
[129]	train-mlogloss:0.31303	eval-mlogloss:0.25910
[130]	train-mlogloss:0.31289	eval-mlogloss:0.25856
[131]	train-mlogloss:0.31296	eval-mlogloss:0.25882
[132]	train-mlogloss:0.31288	eval-mlogloss:0.25856
[133]	train-mlogloss:0.31282	eval-mlogloss:0.25842
[134]	train-mlogloss:0.31283	eval-mlogloss:0.25841
[135]	train-mlogloss:0.31159	eval-mlogloss:0.25731
[136]	train-mlogloss:0.31158	eval-mlogloss:0.25731
[137]	train-mlogloss:0.31158	eval-mlogloss:0.25725
[138]	train-mlogloss:0.31138	eval-mlogloss:0.25691
[139]	train-mlogloss:0.31141	eval-mlogloss:0.25685
[140]	train-mlogloss:0.31142	eval-mlogloss:0.25683
[141]	train-mlogloss:0.31145	eval-mlogloss:0.25681
[142]	train-mlogloss:0.31132	eval-mlogloss:0.25679
[143]	train-mlogloss:0.31123	eval-mlogloss:0.25680
[144]	train-mlogloss:0.31099	eval-mlogloss:0.25683
[145]	train-mlogloss:0.31099	eval-mlogloss:0.25699
[146]	train-mlogloss:0.31095	eval-mlogloss:0.25666
[147]	train-mlogloss:0.31085	eval-mlogloss:0.25669
[148]	train-mlogloss:0.31085	eval-mlogloss:0.25692
[149]	train-mlogloss:0.31087	eval-mlogloss:0.25696
[150]	train-mlogloss:0.31085	eval-mlogloss:0.25676
[151]	train-mlogloss:0.31083	eval-mlogloss:0.25678
[152]	train-mlogloss:0.31082	eval-mlogloss:0.25669
[153]	train-mlogloss:0.31080	eval-mlogloss:0.25662
[154]	train-mlogloss:0.31029	eval-mlogloss:0.25620
[155]	train-mlogloss:0.31026	eval-mlogloss:0.25608
[156]	train-mlogloss:0.31030	eval-mlogloss:0.25610
[157]	train-mlogloss:0.31031	eval-mlogloss:0.25601
[158]	train-mlogloss:0.31030	eval-mlogloss:0.25605
[159]	train-mlogloss:0.31024	eval-mlogloss:0.25610
[160]	train-mlogloss:0.31000	eval-mlogloss:0.25592
[161]	train-mlogloss:0.30998	eval-mlogloss:0.25602
[162]	train-mlogloss:0.30995	eval-mlogloss:0.25601
[163]	train-mlogloss:0.30996	eval-mlogloss:0.25588
[164]	train-mlogloss:0.30967	eval-mlogloss:0.25580
[165]	train-mlogloss:0.30966	eval-mlogloss:0.25563
[166]	train-mlogloss:0.30903	eval-mlogloss:0.25479
[167]	train-mlogloss:0.30904	eval-mlogloss:0.25478
[168]	train-mlogloss:0.30905	eval-mlogloss:0.25479
[169]	train-mlogloss:0.30862	eval-mlogloss:0.25407
[170]	train-mlogloss:0.30861	eval-mlogloss:0.25420
[171]	train-mlogloss:0.30861	eval-mlogloss:0.25442
[172]	train-mlogloss:0.30860	eval-mlogloss:0.25434
[173]	train-mlogloss:0.30860	eval-mlogloss:0.25432
[174]	train-mlogloss:0.30858	eval-mlogloss:0.25441
[175]	train-mlogloss:0.30861	eval-mlogloss:0.25420
[176]	train-mlogloss:0.30863	eval-mlogloss:0.25415
[177]	train-mlogloss:0.30863	eval-mlogloss:0.25421
[178]	train-mlogloss:0.30867	eval-mlogloss:0.25426
[179]	train-mlogloss:0.30873	eval-mlogloss:0.25429
[180]	train-mlogloss:0.30881	eval-mlogloss:0.25431
[181]	train-mlogloss:0.30877	eval-mlogloss:0.25426
[182]	train-mlogloss:0.30877	eval-mlogloss:0.25414
[183]	train-mlogloss:0.30848	eval-mlogloss:0.25326
[184]	train-mlogloss:0.30816	eval-mlogloss:0.25204
[185]	train-mlogloss:0.30817	eval-mlogloss:0.25217
[186]	train-mlogloss:0.30805	eval-mlogloss:0.25165
[187]	train-mlogloss:0.30806	eval-mlogloss:0.25156
[188]	train-mlogloss:0.30804	eval-mlogloss:0.25166
[189]	train-mlogloss:0.30803	eval-mlogloss:0.25181
[190]	train-mlogloss:0.30801	eval-mlogloss:0.25186
[191]	train-mlogloss:0.30802	eval-mlogloss:0.25182
[192]	train-mlogloss:0.30799	eval-mlogloss:0.25184
[193]	train-mlogloss:0.30797	eval-mlogloss:0.25175
[194]	train-mlogloss:0.30796	eval-mlogloss:0.25186
[195]	train-mlogloss:0.30800	eval-mlogloss:0.25176
[196]	train-mlogloss:0.30781	eval-mlogloss:0.25172
[197]	train-mlogloss:0.30779	eval-mlogloss:0.25164
[198]	train-mlogloss:0.30783	eval-mlogloss:0.25144
[199]	train-mlogloss:0.30551	eval-mlogloss:0.24864
[200]	train-mlogloss:0.30551	eval-mlogloss:0.24864
[201]	train-mlogloss:0.30555	eval-mlogloss:0.24852
[202]	train-mlogloss:0.30555	eval-mlogloss:0.24854
[203]	train-mlogloss:0.30528	eval-mlogloss:0.24776
[204]	train-mlogloss:0.30528	eval-mlogloss:0.24777
[205]	train-mlogloss:0.30524	eval-mlogloss:0.24763
[206]	train-mlogloss:0.30473	eval-mlogloss:0.24746
[207]	train-mlogloss:0.30466	eval-mlogloss:0.24736
[208]	train-mlogloss:0.30439	eval-mlogloss:0.24734
[209]	train-mlogloss:0.30445	eval-mlogloss:0.24718
[210]	train-mlogloss:0.30445	eval-mlogloss:0.24721
[211]	train-mlogloss:0.30427	eval-mlogloss:0.24699
[212]	train-mlogloss:0.30424	eval-mlogloss:0.24709
[213]	train-mlogloss:0.30401	eval-mlogloss:0.24685
[214]	train-mlogloss:0.30404	eval-mlogloss:0.24674
[215]	train-mlogloss:0.30369	eval-mlogloss:0.24656
[216]	train-mlogloss:0.30370	eval-mlogloss:0.24650
[217]	train-mlogloss:0.30368	eval-mlogloss:0.24660
[218]	train-mlogloss:0.30365	eval-mlogloss:0.24677
[219]	train-mlogloss:0.30208	eval-mlogloss:0.24542
[220]	train-mlogloss:0.30209	eval-mlogloss:0.24537
[221]	train-mlogloss:0.30198	eval-mlogloss:0.24543
[222]	train-mlogloss:0.30200	eval-mlogloss:0.24541
[223]	train-mlogloss:0.30196	eval-mlogloss:0.24545
[224]	train-mlogloss:0.30191	eval-mlogloss:0.24542
[225]	train-mlogloss:0.30189	eval-mlogloss:0.24550
[226]	train-mlogloss:0.30191	eval-mlogloss:0.24536
[227]	train-mlogloss:0.30189	eval-mlogloss:0.24553
[228]	train-mlogloss:0.30189	eval-mlogloss:0.24550
[229]	train-mlogloss:0.30189	eval-mlogloss:0.24572
[230]	train-mlogloss:0.30191	eval-mlogloss:0.24581
[231]	train-mlogloss:0.30196	eval-mlogloss:0.24586
[232]	train-mlogloss:0.30194	eval-mlogloss:0.24590
[233]	train-mlogloss:0.30193	eval-mlogloss:0.24568
[234]	train-mlogloss:0.30195	eval-mlogloss:0.24577
[235]	train-mlogloss:0.30195	eval-mlogloss:0.24589
[236]	train-mlogloss:0.30197	eval-mlogloss:0.24595
[237]	train-mlogloss:0.30199	eval-mlogloss:0.24606
[238]	train-mlogloss:0.30198	eval-mlogloss:0.24603
[239]	train-mlogloss:0.30179	eval-mlogloss:0.24591
[240]	train-mlogloss:0.30142	eval-mlogloss:0.24494
[241]	train-mlogloss:0.30139	eval-mlogloss:0.24478
[242]	train-mlogloss:0.30143	eval-mlogloss:0.24494
[243]	train-mlogloss:0.30141	eval-mlogloss:0.24490
[244]	train-mlogloss:0.30141	eval-mlogloss:0.24489
[245]	train-mlogloss:0.30129	eval-mlogloss:0.24471
[246]	train-mlogloss:0.30127	eval-mlogloss:0.24437
[247]	train-mlogloss:0.30129	eval-mlogloss:0.24441
[248]	train-mlogloss:0.30130	eval-mlogloss:0.24444
[249]	train-mlogloss:0.30129	eval-mlogloss:0.24429
[250]	train-mlogloss:0.30121	eval-mlogloss:0.24399
[251]	train-mlogloss:0.30126	eval-mlogloss:0.24386
[252]	train-mlogloss:0.30104	eval-mlogloss:0.24358
[253]	train-mlogloss:0.30088	eval-mlogloss:0.24356
[254]	train-mlogloss:0.30088	eval-mlogloss:0.24364
[255]	train-mlogloss:0.30067	eval-mlogloss:0.24354
[256]	train-mlogloss:0.30055	eval-mlogloss:0.24324
[257]	train-mlogloss:0.30053	eval-mlogloss:0.24318
[258]	train-mlogloss:0.30058	eval-mlogloss:0.24310
[259]	train-mlogloss:0.30062	eval-mlogloss:0.24298
[260]	train-mlogloss:0.30064	eval-mlogloss:0.24289
[261]	train-mlogloss:0.30063	eval-mlogloss:0.24291
[262]	train-mlogloss:0.30047	eval-mlogloss:0.24252
[263]	train-mlogloss:0.30042	eval-mlogloss:0.24259
[264]	train-mlogloss:0.30043	eval-mlogloss:0.24257
[265]	train-mlogloss:0.30040	eval-mlogloss:0.24267
[266]	train-mlogloss:0.30033	eval-mlogloss:0.24266
[267]	train-mlogloss:0.30024	eval-mlogloss:0.24253
[268]	train-mlogloss:0.29979	eval-mlogloss:0.24235
[269]	train-mlogloss:0.29965	eval-mlogloss:0.24230
[270]	train-mlogloss:0.29954	eval-mlogloss:0.24152
[271]	train-mlogloss:0.29952	eval-mlogloss:0.24159
[272]	train-mlogloss:0.29943	eval-mlogloss:0.24158
[273]	train-mlogloss:0.29943	eval-mlogloss:0.24165
[274]	train-mlogloss:0.29943	eval-mlogloss:0.24176
[275]	train-mlogloss:0.29944	eval-mlogloss:0.24180
[276]	train-mlogloss:0.29944	eval-mlogloss:0.24183
[277]	train-mlogloss:0.29942	eval-mlogloss:0.24198
[278]	train-mlogloss:0.29936	eval-mlogloss:0.24182
[279]	train-mlogloss:0.29937	eval-mlogloss:0.24185
[280]	train-mlogloss:0.29934	eval-mlogloss:0.24157
[281]	train-mlogloss:0.29934	eval-mlogloss:0.24153
[282]	train-mlogloss:0.29895	eval-mlogloss:0.24114
[283]	train-mlogloss:0.29891	eval-mlogloss:0.24120
[284]	train-mlogloss:0.29889	eval-mlogloss:0.24132
[285]	train-mlogloss:0.29888	eval-mlogloss:0.24142
[286]	train-mlogloss:0.29875	eval-mlogloss:0.24153
[287]	train-mlogloss:0.29875	eval-mlogloss:0.24132
[288]	train-mlogloss:0.29874	eval-mlogloss:0.24131
[289]	train-mlogloss:0.29859	eval-mlogloss:0.24084
[290]	train-mlogloss:0.29859	eval-mlogloss:0.24093
[291]	train-mlogloss:0.29861	eval-mlogloss:0.24106
[292]	train-mlogloss:0.29860	eval-mlogloss:0.24119
[293]	train-mlogloss:0.29862	eval-mlogloss:0.24115
[294]	train-mlogloss:0.29864	eval-mlogloss:0.24120
[295]	train-mlogloss:0.29864	eval-mlogloss:0.24099
[296]	train-mlogloss:0.29862	eval-mlogloss:0.24106
[297]	train-mlogloss:0.29861	eval-mlogloss:0.24107
[298]	train-mlogloss:0.29839	eval-mlogloss:0.24092
[299]	train-mlogloss:0.29836	eval-mlogloss:0.24071

[I 2026-06-28 08:49:16,788] Trial 1 finished with value: 1.0 and parameters: {'lambda': 7.029691454365329e-06, 'alpha': 0.10109136569385263, 'eta': 0.0534695522556219, 'gamma': 0.09072059606783897, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.417589328248868, 'colsample_bytree': 0.5188108025208698}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03614	eval-mlogloss:1.04314

[I 2026-06-28 08:49:16,801] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02003	eval-mlogloss:1.02946

[I 2026-06-28 08:49:16,815] Trial 3 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07451	eval-mlogloss:1.07442
[1]	train-mlogloss:1.05109	eval-mlogloss:1.05034
[2]	train-mlogloss:1.02797	eval-mlogloss:1.02627
[3]	train-mlogloss:1.00587	eval-mlogloss:1.00371
[4]	train-mlogloss:0.98483	eval-mlogloss:0.98230
[5]	train-mlogloss:0.96388	eval-mlogloss:0.95995
[6]	train-mlogloss:0.94379	eval-mlogloss:0.93933
[7]	train-mlogloss:0.92444	eval-mlogloss:0.91935
[8]	train-mlogloss:0.90564	eval-mlogloss:0.90010
[9]	train-mlogloss:0.88734	eval-mlogloss:0.88143
[10]	train-mlogloss:0.86965	eval-mlogloss:0.86331
[11]	train-mlogloss:0.85231	eval-mlogloss:0.84533
[12]	train-mlogloss:0.83579	eval-mlogloss:0.82830
[13]	train-mlogloss:0.81953	eval-mlogloss:0.81122
[14]	train-mlogloss:0.80387	eval-mlogloss:0.79518
[15]	train-mlogloss:0.78858	eval-mlogloss:0.77885
[16]	train-mlogloss:0.77390	eval-mlogloss:0.76346
[17]	train-mlogloss:0.75889	eval-mlogloss:0.74866
[18]	train-mlogloss:0.74458	eval-mlogloss:0.73367
[19]	train-mlogloss:0.73060	eval-mlogloss:0.71884
[20]	train-mlogloss:0.71704	eval-mlogloss:0.70441
[21]	train-mlogloss:0.70455	eval-mlogloss:0.69144
[22]	train-mlogloss:0.69153	eval-mlogloss:0.67791
[23]	train-mlogloss:0.67897	eval-mlogloss:0.66468
[24]	train-mlogloss:0.66676	eval-mlogloss:0.65154
[25]	train-mlogloss:0.65475	eval-mlogloss:0.63881
[26]	train-mlogloss:0.64305	eval-mlogloss:0.62610
[27]	train-mlogloss:0.63158	eval-mlogloss:0.61403
[28]	train-mlogloss:0.62023	eval-mlogloss:0.60218
[29]	train-mlogloss:0.60948	eval-mlogloss:0.59075
[30]	train-mlogloss:0.59873	eval-mlogloss:0.57990
[31]	train-mlogloss:0.58826	eval-mlogloss:0.56893
[32]	train-mlogloss:0.57797	eval-mlogloss:0.55828
[33]	train-mlogloss:0.56833	eval-mlogloss:0.54789
[34]	train-mlogloss:0.55872	eval-mlogloss:0.53802
[35]	train-mlogloss:0.54947	eval-mlogloss:0.52802
[36]	train-mlogloss:0.53999	eval-mlogloss:0.51809
[37]	train-mlogloss:0.53078	eval-mlogloss:0.50860
[38]	train-mlogloss:0.52216	eval-mlogloss:0.49955
[39]	train-mlogloss:0.51342	eval-mlogloss:0.49048
[40]	train-mlogloss:0.50500	eval-mlogloss:0.48184
[41]	train-mlogloss:0.49670	eval-mlogloss:0.47296
[42]	train-mlogloss:0.48865	eval-mlogloss:0.46426
[43]	train-mlogloss:0.48067	eval-mlogloss:0.45586
[44]	train-mlogloss:0.47286	eval-mlogloss:0.44757
[45]	train-mlogloss:0.46527	eval-mlogloss:0.43959
[46]	train-mlogloss:0.45773	eval-mlogloss:0.43185
[47]	train-mlogloss:0.45043	eval-mlogloss:0.42422
[48]	train-mlogloss:0.44339	eval-mlogloss:0.41667
[49]	train-mlogloss:0.43643	eval-mlogloss:0.40931
[50]	train-mlogloss:0.42964	eval-mlogloss:0.40225
[51]	train-mlogloss:0.42313	eval-mlogloss:0.39528
[52]	train-mlogloss:0.41661	eval-mlogloss:0.38813
[53]	train-mlogloss:0.41033	eval-mlogloss:0.38124
[54]	train-mlogloss:0.40400	eval-mlogloss:0.37443
[55]	train-mlogloss:0.39775	eval-mlogloss:0.36789
[56]	train-mlogloss:0.39178	eval-mlogloss:0.36159
[57]	train-mlogloss:0.38592	eval-mlogloss:0.35532
[58]	train-mlogloss:0.37987	eval-mlogloss:0.34985
[59]	train-mlogloss:0.37432	eval-mlogloss:0.34413
[60]	train-mlogloss:0.36893	eval-mlogloss:0.33848
[61]	train-mlogloss:0.36351	eval-mlogloss:0.33293
[62]	train-mlogloss:0.35813	eval-mlogloss:0.32759
[63]	train-mlogloss:0.35302	eval-mlogloss:0.32194
[64]	train-mlogloss:0.34796	eval-mlogloss:0.31634
[65]	train-mlogloss:0.34297	eval-mlogloss:0.31104
[66]	train-mlogloss:0.33804	eval-mlogloss:0.30577
[67]	train-mlogloss:0.33317	eval-mlogloss:0.30037
[68]	train-mlogloss:0.32847	eval-mlogloss:0.29540
[69]	train-mlogloss:0.32385	eval-mlogloss:0.29076
[70]	train-mlogloss:0.31933	eval-mlogloss:0.28607
[71]	train-mlogloss:0.31482	eval-mlogloss:0.28129
[72]	train-mlogloss:0.31046	eval-mlogloss:0.27670
[73]	train-mlogloss:0.30625	eval-mlogloss:0.27212
[74]	train-mlogloss:0.30200	eval-mlogloss:0.26779
[75]	train-mlogloss:0.29787	eval-mlogloss:0.26399
[76]	train-mlogloss:0.29383	eval-mlogloss:0.25945
[77]	train-mlogloss:0.28991	eval-mlogloss:0.25491
[78]	train-mlogloss:0.28589	eval-mlogloss:0.25072
[79]	train-mlogloss:0.28203	eval-mlogloss:0.24654
[80]	train-mlogloss:0.27826	eval-mlogloss:0.24265
[81]	train-mlogloss:0.27464	eval-mlogloss:0.23877
[82]	train-mlogloss:0.27099	eval-mlogloss:0.23509
[83]	train-mlogloss:0.26739	eval-mlogloss:0.23134
[84]	train-mlogloss:0.26390	eval-mlogloss:0.22775
[85]	train-mlogloss:0.26050	eval-mlogloss:0.22397
[86]	train-mlogloss:0.25723	eval-mlogloss:0.22044
[87]	train-mlogloss:0.25398	eval-mlogloss:0.21678
[88]	train-mlogloss:0.25073	eval-mlogloss:0.21336
[89]	train-mlogloss:0.24754	eval-mlogloss:0.21019
[90]	train-mlogloss:0.24442	eval-mlogloss:0.20693
[91]	train-mlogloss:0.24138	eval-mlogloss:0.20362
[92]	train-mlogloss:0.23835	eval-mlogloss:0.20045
[93]	train-mlogloss:0.23549	eval-mlogloss:0.19750
[94]	train-mlogloss:0.23256	eval-mlogloss:0.19448
[95]	train-mlogloss:0.22975	eval-mlogloss:0.19144
[96]	train-mlogloss:0.22695	eval-mlogloss:0.18876
[97]	train-mlogloss:0.22418	eval-mlogloss:0.18569
[98]	train-mlogloss:0.22168	eval-mlogloss:0.18278
[99]	train-mlogloss:0.21907	eval-mlogloss:0.18026
[100]	train-mlogloss:0.21644	eval-mlogloss:0.17759
[101]	train-mlogloss:0.21400	eval-mlogloss:0.17491
[102]	train-mlogloss:0.21151	eval-mlogloss:0.17227
[103]	train-mlogloss:0.20902	eval-mlogloss:0.16962
[104]	train-mlogloss:0.20654	eval-mlogloss:0.16703
[105]	train-mlogloss:0.20440	eval-mlogloss:0.16469
[106]	train-mlogloss:0.20213	eval-mlogloss:0.16249
[107]	train-mlogloss:0.20008	eval-mlogloss:0.16016
[108]	train-mlogloss:0.19804	eval-mlogloss:0.15789
[109]	train-mlogloss:0.19587	eval-mlogloss:0.15545
[110]	train-mlogloss:0.19373	eval-mlogloss:0.15307
[111]	train-mlogloss:0.19181	eval-mlogloss:0.15089
[112]	train-mlogloss:0.18966	eval-mlogloss:0.14876
[113]	train-mlogloss:0.18783	eval-mlogloss:0.14665
[114]	train-mlogloss:0.18588	eval-mlogloss:0.14481
[115]	train-mlogloss:0.18402	eval-mlogloss:0.14288
[116]	train-mlogloss:0.18223	eval-mlogloss:0.14088
[117]	train-mlogloss:0.18035	eval-mlogloss:0.13868
[118]	train-mlogloss:0.17861	eval-mlogloss:0.13686
[119]	train-mlogloss:0.17684	eval-mlogloss:0.13514
[120]	train-mlogloss:0.17515	eval-mlogloss:0.13326
[121]	train-mlogloss:0.17346	eval-mlogloss:0.13160
[122]	train-mlogloss:0.17182	eval-mlogloss:0.12971
[123]	train-mlogloss:0.17024	eval-mlogloss:0.12809
[124]	train-mlogloss:0.16857	eval-mlogloss:0.12636
[125]	train-mlogloss:0.16696	eval-mlogloss:0.12466
[126]	train-mlogloss:0.16540	eval-mlogloss:0.12332
[127]	train-mlogloss:0.16394	eval-mlogloss:0.12187
[128]	train-mlogloss:0.16254	eval-mlogloss:0.12010
[129]	train-mlogloss:0.16111	eval-mlogloss:0.11851
[130]	train-mlogloss:0.15962	eval-mlogloss:0.11709
[131]	train-mlogloss:0.15822	eval-mlogloss:0.11545
[132]	train-mlogloss:0.15695	eval-mlogloss:0.11403
[133]	train-mlogloss:0.15572	eval-mlogloss:0.11291
[134]	train-mlogloss:0.15455	eval-mlogloss:0.11139
[135]	train-mlogloss:0.15342	eval-mlogloss:0.10990
[136]	train-mlogloss:0.15217	eval-mlogloss:0.10874
[137]	train-mlogloss:0.15106	eval-mlogloss:0.10763
[138]	train-mlogloss:0.15002	eval-mlogloss:0.10627
[139]	train-mlogloss:0.14879	eval-mlogloss:0.10496
[140]	train-mlogloss:0.14772	eval-mlogloss:0.10388
[141]	train-mlogloss:0.14671	eval-mlogloss:0.10269
[142]	train-mlogloss:0.14554	eval-mlogloss:0.10146
[143]	train-mlogloss:0.14436	eval-mlogloss:0.10028
[144]	train-mlogloss:0.14340	eval-mlogloss:0.09915
[145]	train-mlogloss:0.14251	eval-mlogloss:0.09826
[146]	train-mlogloss:0.14146	eval-mlogloss:0.09705
[147]	train-mlogloss:0.14049	eval-mlogloss:0.09578
[148]	train-mlogloss:0.13975	eval-mlogloss:0.09491
[149]	train-mlogloss:0.13869	eval-mlogloss:0.09394
[150]	train-mlogloss:0.13770	eval-mlogloss:0.09277
[151]	train-mlogloss:0.13698	eval-mlogloss:0.09197
[152]	train-mlogloss:0.13610	eval-mlogloss:0.09117
[153]	train-mlogloss:0.13518	eval-mlogloss:0.09006
[154]	train-mlogloss:0.13434	eval-mlogloss:0.08907
[155]	train-mlogloss:0.13352	eval-mlogloss:0.08813
[156]	train-mlogloss:0.13286	eval-mlogloss:0.08742
[157]	train-mlogloss:0.13229	eval-mlogloss:0.08656
[158]	train-mlogloss:0.13154	eval-mlogloss:0.08581
[159]	train-mlogloss:0.13082	eval-mlogloss:0.08479
[160]	train-mlogloss:0.13024	eval-mlogloss:0.08408
[161]	train-mlogloss:0.12997	eval-mlogloss:0.08378
[162]	train-mlogloss:0.12955	eval-mlogloss:0.08332
[163]	train-mlogloss:0.12921	eval-mlogloss:0.08285
[164]	train-mlogloss:0.12856	eval-mlogloss:0.08211
[165]	train-mlogloss:0.12823	eval-mlogloss:0.08151
[166]	train-mlogloss:0.12795	eval-mlogloss:0.08108
[167]	train-mlogloss:0.12767	eval-mlogloss:0.08072
[168]	train-mlogloss:0.12727	eval-mlogloss:0.08031
[169]	train-mlogloss:0.12702	eval-mlogloss:0.07991
[170]	train-mlogloss:0.12677	eval-mlogloss:0.07962
[171]	train-mlogloss:0.12636	eval-mlogloss:0.07909
[172]	train-mlogloss:0.12615	eval-mlogloss:0.07872
[173]	train-mlogloss:0.12588	eval-mlogloss:0.07833
[174]	train-mlogloss:0.12565	eval-mlogloss:0.07795
[175]	train-mlogloss:0.12544	eval-mlogloss:0.07775
[176]	train-mlogloss:0.12474	eval-mlogloss:0.07687
[177]	train-mlogloss:0.12453	eval-mlogloss:0.07659
[178]	train-mlogloss:0.12430	eval-mlogloss:0.07643
[179]	train-mlogloss:0.12404	eval-mlogloss:0.07605
[180]	train-mlogloss:0.12388	eval-mlogloss:0.07576
[181]	train-mlogloss:0.12354	eval-mlogloss:0.07520
[182]	train-mlogloss:0.12317	eval-mlogloss:0.07471
[183]	train-mlogloss:0.12290	eval-mlogloss:0.07429
[184]	train-mlogloss:0.12269	eval-mlogloss:0.07396
[185]	train-mlogloss:0.12248	eval-mlogloss:0.07364
[186]	train-mlogloss:0.12224	eval-mlogloss:0.07341
[187]	train-mlogloss:0.12200	eval-mlogloss:0.07305
[188]	train-mlogloss:0.12182	eval-mlogloss:0.07278
[189]	train-mlogloss:0.12158	eval-mlogloss:0.07234
[190]	train-mlogloss:0.12134	eval-mlogloss:0.07203
[191]	train-mlogloss:0.12115	eval-mlogloss:0.07182
[192]	train-mlogloss:0.12092	eval-mlogloss:0.07148
[193]	train-mlogloss:0.12069	eval-mlogloss:0.07107
[194]	train-mlogloss:0.12043	eval-mlogloss:0.07082
[195]	train-mlogloss:0.12030	eval-mlogloss:0.07074
[196]	train-mlogloss:0.12016	eval-mlogloss:0.07077
[197]	train-mlogloss:0.12000	eval-mlogloss:0.07045
[198]	train-mlogloss:0.11981	eval-mlogloss:0.07012
[199]	train-mlogloss:0.11966	eval-mlogloss:0.06994
[200]	train-mlogloss:0.11946	eval-mlogloss:0.06958
[201]	train-mlogloss:0.11928	eval-mlogloss:0.06928
[202]	train-mlogloss:0.11917	eval-mlogloss:0.06917
[203]	train-mlogloss:0.11905	eval-mlogloss:0.06917
[204]	train-mlogloss:0.11887	eval-mlogloss:0.06892
[205]	train-mlogloss:0.11871	eval-mlogloss:0.06868
[206]	train-mlogloss:0.11851	eval-mlogloss:0.06843
[207]	train-mlogloss:0.11822	eval-mlogloss:0.06804
[208]	train-mlogloss:0.11805	eval-mlogloss:0.06788
[209]	train-mlogloss:0.11790	eval-mlogloss:0.06786
[210]	train-mlogloss:0.11777	eval-mlogloss:0.06759
[211]	train-mlogloss:0.11763	eval-mlogloss:0.06745
[212]	train-mlogloss:0.11743	eval-mlogloss:0.06716
[213]	train-mlogloss:0.11733	eval-mlogloss:0.06717
[214]	train-mlogloss:0.11721	eval-mlogloss:0.06709
[215]	train-mlogloss:0.11701	eval-mlogloss:0.06682
[216]	train-mlogloss:0.11688	eval-mlogloss:0.06649
[217]	train-mlogloss:0.11670	eval-mlogloss:0.06618
[218]	train-mlogloss:0.11657	eval-mlogloss:0.06619
[219]	train-mlogloss:0.11639	eval-mlogloss:0.06605
[220]	train-mlogloss:0.11628	eval-mlogloss:0.06606
[221]	train-mlogloss:0.11615	eval-mlogloss:0.06610
[222]	train-mlogloss:0.11593	eval-mlogloss:0.06592
[223]	train-mlogloss:0.11579	eval-mlogloss:0.06561
[224]	train-mlogloss:0.11561	eval-mlogloss:0.06532
[225]	train-mlogloss:0.11544	eval-mlogloss:0.06509
[226]	train-mlogloss:0.11528	eval-mlogloss:0.06492
[227]	train-mlogloss:0.11517	eval-mlogloss:0.06481
[228]	train-mlogloss:0.11499	eval-mlogloss:0.06456
[229]	train-mlogloss:0.11488	eval-mlogloss:0.06444
[230]	train-mlogloss:0.11474	eval-mlogloss:0.06416
[231]	train-mlogloss:0.11462	eval-mlogloss:0.06398
[232]	train-mlogloss:0.11451	eval-mlogloss:0.06402
[233]	train-mlogloss:0.11436	eval-mlogloss:0.06407
[234]	train-mlogloss:0.11425	eval-mlogloss:0.06415
[235]	train-mlogloss:0.11414	eval-mlogloss:0.06400
[236]	train-mlogloss:0.11397	eval-mlogloss:0.06376
[237]	train-mlogloss:0.11387	eval-mlogloss:0.06361
[238]	train-mlogloss:0.11373	eval-mlogloss:0.06339
[239]	train-mlogloss:0.11363	eval-mlogloss:0.06324
[240]	train-mlogloss:0.11349	eval-mlogloss:0.06331
[241]	train-mlogloss:0.11339	eval-mlogloss:0.06331
[242]	train-mlogloss:0.11325	eval-mlogloss:0.06337
[243]	train-mlogloss:0.11310	eval-mlogloss:0.06307
[244]	train-mlogloss:0.11297	eval-mlogloss:0.06312
[245]	train-mlogloss:0.11283	eval-mlogloss:0.06290
[246]	train-mlogloss:0.11272	eval-mlogloss:0.06291
[247]	train-mlogloss:0.11258	eval-mlogloss:0.06273
[248]	train-mlogloss:0.11246	eval-mlogloss:0.06250
[249]	train-mlogloss:0.11232	eval-mlogloss:0.06225
[250]	train-mlogloss:0.11217	eval-mlogloss:0.06200
[251]	train-mlogloss:0.11202	eval-mlogloss:0.06170
[252]	train-mlogloss:0.11192	eval-mlogloss:0.06169
[253]	train-mlogloss:0.11179	eval-mlogloss:0.06175
[254]	train-mlogloss:0.11166	eval-mlogloss:0.06159
[255]	train-mlogloss:0.11154	eval-mlogloss:0.06140

[I 2026-06-28 08:49:17,790] Trial 4 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:0.96592	eval-mlogloss:0.98017

[I 2026-06-28 08:49:17,801] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.77259	eval-mlogloss:0.74985

[I 2026-06-28 08:49:17,818] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.86152	eval-mlogloss:0.84679

[I 2026-06-28 08:49:17,833] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06961	eval-mlogloss:1.07428
[1]	train-mlogloss:1.02118	eval-mlogloss:1.02215
[2]	train-mlogloss:0.98148	eval-mlogloss:0.98081
[3]	train-mlogloss:0.94051	eval-mlogloss:0.93148

[I 2026-06-28 08:49:17,864] Trial 8 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.84427	eval-mlogloss:0.83415

[I 2026-06-28 08:49:17,881] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99838	eval-mlogloss:0.99733

[I 2026-06-28 08:49:17,931] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01901	eval-mlogloss:1.02003

[I 2026-06-28 08:49:17,976] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07508	eval-mlogloss:1.07603
[1]	train-mlogloss:1.04454	eval-mlogloss:1.04383
[2]	train-mlogloss:1.01513	eval-mlogloss:1.01270
[3]	train-mlogloss:0.98550	eval-mlogloss:0.98232

[I 2026-06-28 08:49:18,021] Trial 12 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.97088	eval-mlogloss:0.97068

[I 2026-06-28 08:49:18,067] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03515	eval-mlogloss:1.03551

[I 2026-06-28 08:49:18,103] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84616	eval-mlogloss:0.84324

[I 2026-06-28 08:49:18,129] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.94160	eval-mlogloss:0.94164

[I 2026-06-28 08:49:18,156] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99529	eval-mlogloss:0.99537

[I 2026-06-28 08:49:18,188] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04537	eval-mlogloss:1.04346

[I 2026-06-28 08:49:18,219] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05933	eval-mlogloss:1.05857

[I 2026-06-28 08:49:18,244] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97711	eval-mlogloss:0.98246

[I 2026-06-28 08:49:18,271] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08446	eval-mlogloss:1.08560
[1]	train-mlogloss:1.07081	eval-mlogloss:1.07148
[2]	train-mlogloss:1.05699	eval-mlogloss:1.05702
[3]	train-mlogloss:1.04344	eval-mlogloss:1.04260
[4]	train-mlogloss:1.03030	eval-mlogloss:1.02907
[5]	train-mlogloss:1.01726	eval-mlogloss:1.01528
[6]	train-mlogloss:1.00450	eval-mlogloss:1.00183
[7]	train-mlogloss:0.99221	eval-mlogloss:0.98907
[8]	train-mlogloss:0.98000	eval-mlogloss:0.97639
[9]	train-mlogloss:0.96811	eval-mlogloss:0.96382
[10]	train-mlogloss:0.95631	eval-mlogloss:0.95141
[11]	train-mlogloss:0.94466	eval-mlogloss:0.93907
[12]	train-mlogloss:0.93345	eval-mlogloss:0.92770
[13]	train-mlogloss:0.92242	eval-mlogloss:0.91600
[14]	train-mlogloss:0.91165	eval-mlogloss:0.90531
[15]	train-mlogloss:0.90082	eval-mlogloss:0.89373
[16]	train-mlogloss:0.89036	eval-mlogloss:0.88349
[17]	train-mlogloss:0.88000	eval-mlogloss:0.87306
[18]	train-mlogloss:0.86964	eval-mlogloss:0.86212
[19]	train-mlogloss:0.85952	eval-mlogloss:0.85142
[20]	train-mlogloss:0.84954	eval-mlogloss:0.84073
[21]	train-mlogloss:0.83953	eval-mlogloss:0.83012
[22]	train-mlogloss:0.82982	eval-mlogloss:0.81970
[23]	train-mlogloss:0.82039	eval-mlogloss:0.80964
[24]	train-mlogloss:0.81120	eval-mlogloss:0.79984
[25]	train-mlogloss:0.80185	eval-mlogloss:0.78965
[26]	train-mlogloss:0.79286	eval-mlogloss:0.78004
[27]	train-mlogloss:0.78400	eval-mlogloss:0.77084
[28]	train-mlogloss:0.77512	eval-mlogloss:0.76172
[29]	train-mlogloss:0.76643	eval-mlogloss:0.75254
[30]	train-mlogloss:0.75794	eval-mlogloss:0.74357
[31]	train-mlogloss:0.74951	eval-mlogloss:0.73472
[32]	train-mlogloss:0.74131	eval-mlogloss:0.72605
[33]	train-mlogloss:0.73333	eval-mlogloss:0.71751
[34]	train-mlogloss:0.72521	eval-mlogloss:0.70914
[35]	train-mlogloss:0.71745	eval-mlogloss:0.70104
[36]	train-mlogloss:0.70961	eval-mlogloss:0.69293
[37]	train-mlogloss:0.70201	eval-mlogloss:0.68484
[38]	train-mlogloss:0.69460	eval-mlogloss:0.67691
[39]	train-mlogloss:0.68704	eval-mlogloss:0.66906
[40]	train-mlogloss:0.67971	eval-mlogloss:0.66138
[41]	train-mlogloss:0.67245	eval-mlogloss:0.65385
[42]	train-mlogloss:0.66536	eval-mlogloss:0.64646
[43]	train-mlogloss:0.65822	eval-mlogloss:0.63960
[44]	train-mlogloss:0.65136	eval-mlogloss:0.63255
[45]	train-mlogloss:0.64443	eval-mlogloss:0.62533
[46]	train-mlogloss:0.63745	eval-mlogloss:0.61795
[47]	train-mlogloss:0.63071	eval-mlogloss:0.61104
[48]	train-mlogloss:0.62415	eval-mlogloss:0.60414
[49]	train-mlogloss:0.61771	eval-mlogloss:0.59727
[50]	train-mlogloss:0.61119	eval-mlogloss:0.59036
[51]	train-mlogloss:0.60495	eval-mlogloss:0.58392
[52]	train-mlogloss:0.59866	eval-mlogloss:0.57721
[53]	train-mlogloss:0.59257	eval-mlogloss:0.57082
[54]	train-mlogloss:0.58636	eval-mlogloss:0.56440
[55]	train-mlogloss:0.58030	eval-mlogloss:0.55776
[56]	train-mlogloss:0.57442	eval-mlogloss:0.55140
[57]	train-mlogloss:0.56862	eval-mlogloss:0.54533
[58]	train-mlogloss:0.56264	eval-mlogloss:0.53897
[59]	train-mlogloss:0.55690	eval-mlogloss:0.53300
[60]	train-mlogloss:0.55124	eval-mlogloss:0.52707
[61]	train-mlogloss:0.54574	eval-mlogloss:0.52140
[62]	train-mlogloss:0.54035	eval-mlogloss:0.51587
[63]	train-mlogloss:0.53499	eval-mlogloss:0.51024
[64]	train-mlogloss:0.52973	eval-mlogloss:0.50478
[65]	train-mlogloss:0.52448	eval-mlogloss:0.49950
[66]	train-mlogloss:0.51938	eval-mlogloss:0.49416
[67]	train-mlogloss:0.51425	eval-mlogloss:0.48875
[68]	train-mlogloss:0.50913	eval-mlogloss:0.48338
[69]	train-mlogloss:0.50404	eval-mlogloss:0.47804
[70]	train-mlogloss:0.49902	eval-mlogloss:0.47278
[71]	train-mlogloss:0.49423	eval-mlogloss:0.46786
[72]	train-mlogloss:0.48947	eval-mlogloss:0.46303
[73]	train-mlogloss:0.48477	eval-mlogloss:0.45806
[74]	train-mlogloss:0.48003	eval-mlogloss:0.45319
[75]	train-mlogloss:0.47548	eval-mlogloss:0.44841
[76]	train-mlogloss:0.47093	eval-mlogloss:0.44374
[77]	train-mlogloss:0.46642	eval-mlogloss:0.43905
[78]	train-mlogloss:0.46201	eval-mlogloss:0.43425
[79]	train-mlogloss:0.45762	eval-mlogloss:0.42961
[80]	train-mlogloss:0.45306	eval-mlogloss:0.42517
[81]	train-mlogloss:0.44867	eval-mlogloss:0.42073
[82]	train-mlogloss:0.44442	eval-mlogloss:0.41635
[83]	train-mlogloss:0.44031	eval-mlogloss:0.41202
[84]	train-mlogloss:0.43618	eval-mlogloss:0.40739
[85]	train-mlogloss:0.43211	eval-mlogloss:0.40326
[86]	train-mlogloss:0.42802	eval-mlogloss:0.39898
[87]	train-mlogloss:0.42407	eval-mlogloss:0.39484
[88]	train-mlogloss:0.42005	eval-mlogloss:0.39045
[89]	train-mlogloss:0.41613	eval-mlogloss:0.38630
[90]	train-mlogloss:0.41219	eval-mlogloss:0.38229
[91]	train-mlogloss:0.40850	eval-mlogloss:0.37857
[92]	train-mlogloss:0.40474	eval-mlogloss:0.37473
[93]	train-mlogloss:0.40109	eval-mlogloss:0.37143
[94]	train-mlogloss:0.39748	eval-mlogloss:0.36745
[95]	train-mlogloss:0.39373	eval-mlogloss:0.36384
[96]	train-mlogloss:0.39000	eval-mlogloss:0.35982
[97]	train-mlogloss:0.38639	eval-mlogloss:0.35599
[98]	train-mlogloss:0.38285	eval-mlogloss:0.35227
[99]	train-mlogloss:0.37941	eval-mlogloss:0.34883
[100]	train-mlogloss:0.37592	eval-mlogloss:0.34579
[101]	train-mlogloss:0.37253	eval-mlogloss:0.34236
[102]	train-mlogloss:0.36920	eval-mlogloss:0.33895
[103]	train-mlogloss:0.36584	eval-mlogloss:0.33530
[104]	train-mlogloss:0.36250	eval-mlogloss:0.33172
[105]	train-mlogloss:0.35929	eval-mlogloss:0.32848
[106]	train-mlogloss:0.35603	eval-mlogloss:0.32513
[107]	train-mlogloss:0.35290	eval-mlogloss:0.32172
[108]	train-mlogloss:0.34994	eval-mlogloss:0.31859
[109]	train-mlogloss:0.34677	eval-mlogloss:0.31521
[110]	train-mlogloss:0.34363	eval-mlogloss:0.31179
[111]	train-mlogloss:0.34065	eval-mlogloss:0.30861
[112]	train-mlogloss:0.33767	eval-mlogloss:0.30558
[113]	train-mlogloss:0.33476	eval-mlogloss:0.30244
[114]	train-mlogloss:0.33170	eval-mlogloss:0.29976
[115]	train-mlogloss:0.32867	eval-mlogloss:0.29693
[116]	train-mlogloss:0.32567	eval-mlogloss:0.29371
[117]	train-mlogloss:0.32281	eval-mlogloss:0.29074
[118]	train-mlogloss:0.32002	eval-mlogloss:0.28777
[119]	train-mlogloss:0.31718	eval-mlogloss:0.28509
[120]	train-mlogloss:0.31436	eval-mlogloss:0.28228
[121]	train-mlogloss:0.31162	eval-mlogloss:0.27944
[122]	train-mlogloss:0.30885	eval-mlogloss:0.27674
[123]	train-mlogloss:0.30618	eval-mlogloss:0.27404
[124]	train-mlogloss:0.30355	eval-mlogloss:0.27160
[125]	train-mlogloss:0.30087	eval-mlogloss:0.26932
[126]	train-mlogloss:0.29829	eval-mlogloss:0.26671
[127]	train-mlogloss:0.29570	eval-mlogloss:0.26424
[128]	train-mlogloss:0.29326	eval-mlogloss:0.26162
[129]	train-mlogloss:0.29076	eval-mlogloss:0.25921
[130]	train-mlogloss:0.28832	eval-mlogloss:0.25687
[131]	train-mlogloss:0.28584	eval-mlogloss:0.25439
[132]	train-mlogloss:0.28342	eval-mlogloss:0.25214
[133]	train-mlogloss:0.28107	eval-mlogloss:0.24975
[134]	train-mlogloss:0.27876	eval-mlogloss:0.24736
[135]	train-mlogloss:0.27647	eval-mlogloss:0.24511
[136]	train-mlogloss:0.27405	eval-mlogloss:0.24294
[137]	train-mlogloss:0.27174	eval-mlogloss:0.24069
[138]	train-mlogloss:0.26952	eval-mlogloss:0.23848
[139]	train-mlogloss:0.26728	eval-mlogloss:0.23614
[140]	train-mlogloss:0.26500	eval-mlogloss:0.23402
[141]	train-mlogloss:0.26290	eval-mlogloss:0.23167
[142]	train-mlogloss:0.26076	eval-mlogloss:0.22958
[143]	train-mlogloss:0.25863	eval-mlogloss:0.22757
[144]	train-mlogloss:0.25663	eval-mlogloss:0.22535
[145]	train-mlogloss:0.25458	eval-mlogloss:0.22324
[146]	train-mlogloss:0.25253	eval-mlogloss:0.22108
[147]	train-mlogloss:0.25052	eval-mlogloss:0.21901
[148]	train-mlogloss:0.24853	eval-mlogloss:0.21702
[149]	train-mlogloss:0.24630	eval-mlogloss:0.21548
[150]	train-mlogloss:0.24428	eval-mlogloss:0.21359
[151]	train-mlogloss:0.24234	eval-mlogloss:0.21157
[152]	train-mlogloss:0.24030	eval-mlogloss:0.20983
[153]	train-mlogloss:0.23840	eval-mlogloss:0.20789
[154]	train-mlogloss:0.23636	eval-mlogloss:0.20636
[155]	train-mlogloss:0.23445	eval-mlogloss:0.20443
[156]	train-mlogloss:0.23262	eval-mlogloss:0.20260
[157]	train-mlogloss:0.23080	eval-mlogloss:0.20061
[158]	train-mlogloss:0.22895	eval-mlogloss:0.19888
[159]	train-mlogloss:0.22717	eval-mlogloss:0.19724
[160]	train-mlogloss:0.22548	eval-mlogloss:0.19546
[161]	train-mlogloss:0.22366	eval-mlogloss:0.19383
[162]	train-mlogloss:0.22192	eval-mlogloss:0.19229
[163]	train-mlogloss:0.22014	eval-mlogloss:0.19065
[164]	train-mlogloss:0.21838	eval-mlogloss:0.18903
[165]	train-mlogloss:0.21663	eval-mlogloss:0.18707
[166]	train-mlogloss:0.21496	eval-mlogloss:0.18529
[167]	train-mlogloss:0.21312	eval-mlogloss:0.18383
[168]	train-mlogloss:0.21135	eval-mlogloss:0.18249
[169]	train-mlogloss:0.20972	eval-mlogloss:0.18094
[170]	train-mlogloss:0.20809	eval-mlogloss:0.17944
[171]	train-mlogloss:0.20650	eval-mlogloss:0.17802
[172]	train-mlogloss:0.20491	eval-mlogloss:0.17662
[173]	train-mlogloss:0.20333	eval-mlogloss:0.17497
[174]	train-mlogloss:0.20186	eval-mlogloss:0.17331
[175]	train-mlogloss:0.20019	eval-mlogloss:0.17187
[176]	train-mlogloss:0.19870	eval-mlogloss:0.17022
[177]	train-mlogloss:0.19723	eval-mlogloss:0.16885
[178]	train-mlogloss:0.19579	eval-mlogloss:0.16767
[179]	train-mlogloss:0.19427	eval-mlogloss:0.16631
[180]	train-mlogloss:0.19285	eval-mlogloss:0.16500
[181]	train-mlogloss:0.19136	eval-mlogloss:0.16330
[182]	train-mlogloss:0.18995	eval-mlogloss:0.16204
[183]	train-mlogloss:0.18854	eval-mlogloss:0.16052
[184]	train-mlogloss:0.18706	eval-mlogloss:0.15893
[185]	train-mlogloss:0.18556	eval-mlogloss:0.15788
[186]	train-mlogloss:0.18417	eval-mlogloss:0.15645
[187]	train-mlogloss:0.18282	eval-mlogloss:0.15523
[188]	train-mlogloss:0.18152	eval-mlogloss:0.15373
[189]	train-mlogloss:0.18007	eval-mlogloss:0.15275
[190]	train-mlogloss:0.17863	eval-mlogloss:0.15170
[191]	train-mlogloss:0.17743	eval-mlogloss:0.15047
[192]	train-mlogloss:0.17603	eval-mlogloss:0.14927
[193]	train-mlogloss:0.17477	eval-mlogloss:0.14793
[194]	train-mlogloss:0.17337	eval-mlogloss:0.14677
[195]	train-mlogloss:0.17210	eval-mlogloss:0.14557
[196]	train-mlogloss:0.17083	eval-mlogloss:0.14454
[197]	train-mlogloss:0.16962	eval-mlogloss:0.14314
[198]	train-mlogloss:0.16842	eval-mlogloss:0.14193
[199]	train-mlogloss:0.16723	eval-mlogloss:0.14062
[200]	train-mlogloss:0.16607	eval-mlogloss:0.13927
[201]	train-mlogloss:0.16495	eval-mlogloss:0.13802
[202]	train-mlogloss:0.16374	eval-mlogloss:0.13708
[203]	train-mlogloss:0.16249	eval-mlogloss:0.13587
[204]	train-mlogloss:0.16131	eval-mlogloss:0.13494
[205]	train-mlogloss:0.16022	eval-mlogloss:0.13390
[206]	train-mlogloss:0.15916	eval-mlogloss:0.13279
[207]	train-mlogloss:0.15802	eval-mlogloss:0.13179
[208]	train-mlogloss:0.15683	eval-mlogloss:0.13087
[209]	train-mlogloss:0.15574	eval-mlogloss:0.12992
[210]	train-mlogloss:0.15477	eval-mlogloss:0.12889
[211]	train-mlogloss:0.15374	eval-mlogloss:0.12790
[212]	train-mlogloss:0.15268	eval-mlogloss:0.12688
[213]	train-mlogloss:0.15159	eval-mlogloss:0.12586
[214]	train-mlogloss:0.15041	eval-mlogloss:0.12521
[215]	train-mlogloss:0.14935	eval-mlogloss:0.12425
[216]	train-mlogloss:0.14833	eval-mlogloss:0.12310
[217]	train-mlogloss:0.14741	eval-mlogloss:0.12202
[218]	train-mlogloss:0.14649	eval-mlogloss:0.12105
[219]	train-mlogloss:0.14547	eval-mlogloss:0.12009
[220]	train-mlogloss:0.14454	eval-mlogloss:0.11935
[221]	train-mlogloss:0.14357	eval-mlogloss:0.11856
[222]	train-mlogloss:0.14259	eval-mlogloss:0.11774
[223]	train-mlogloss:0.14154	eval-mlogloss:0.11684
[224]	train-mlogloss:0.14059	eval-mlogloss:0.11573
[225]	train-mlogloss:0.13969	eval-mlogloss:0.11487
[226]	train-mlogloss:0.13875	eval-mlogloss:0.11386
[227]	train-mlogloss:0.13780	eval-mlogloss:0.11283
[228]	train-mlogloss:0.13684	eval-mlogloss:0.11198
[229]	train-mlogloss:0.13606	eval-mlogloss:0.11120
[230]	train-mlogloss:0.13520	eval-mlogloss:0.11042
[231]	train-mlogloss:0.13432	eval-mlogloss:0.10944
[232]	train-mlogloss:0.13351	eval-mlogloss:0.10853
[233]	train-mlogloss:0.13268	eval-mlogloss:0.10770
[234]	train-mlogloss:0.13191	eval-mlogloss:0.10692
[235]	train-mlogloss:0.13119	eval-mlogloss:0.10610
[236]	train-mlogloss:0.13035	eval-mlogloss:0.10544
[237]	train-mlogloss:0.12949	eval-mlogloss:0.10472
[238]	train-mlogloss:0.12864	eval-mlogloss:0.10383
[239]	train-mlogloss:0.12782	eval-mlogloss:0.10297
[240]	train-mlogloss:0.12706	eval-mlogloss:0.10221
[241]	train-mlogloss:0.12625	eval-mlogloss:0.10165
[242]	train-mlogloss:0.12546	eval-mlogloss:0.10088
[243]	train-mlogloss:0.12463	eval-mlogloss:0.10022
[244]	train-mlogloss:0.12386	eval-mlogloss:0.09966
[245]	train-mlogloss:0.12312	eval-mlogloss:0.09878
[246]	train-mlogloss:0.12232	eval-mlogloss:0.09827
[247]	train-mlogloss:0.12157	eval-mlogloss:0.09751
[248]	train-mlogloss:0.12082	eval-mlogloss:0.09695
[249]	train-mlogloss:0.12018	eval-mlogloss:0.09620
[250]	train-mlogloss:0.11946	eval-mlogloss:0.09538
[251]	train-mlogloss:0.11876	eval-mlogloss:0.09457
[252]	train-mlogloss:0.11804	eval-mlogloss:0.09381
[253]	train-mlogloss:0.11739	eval-mlogloss:0.09316
[254]	train-mlogloss:0.11674	eval-mlogloss:0.09246
[255]	train-mlogloss:0.11601	eval-mlogloss:0.09189

[I 2026-06-28 08:49:19,342] Trial 21 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.08187	eval-mlogloss:1.08287
[1]	train-mlogloss:1.06570	eval-mlogloss:1.06614
[2]	train-mlogloss:1.04945	eval-mlogloss:1.04915
[3]	train-mlogloss:1.03358	eval-mlogloss:1.03225

[I 2026-06-28 08:49:19,393] Trial 22 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03693	eval-mlogloss:1.03474

[I 2026-06-28 08:49:19,441] Trial 23 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06443	eval-mlogloss:1.07376

[I 2026-06-28 08:49:19,582] Trial 24 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00633	eval-mlogloss:1.00781

[I 2026-06-28 08:49:19,630] Trial 25 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05057	eval-mlogloss:1.04864

[I 2026-06-28 08:49:19,659] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03209	eval-mlogloss:1.02977

[I 2026-06-28 08:49:19,690] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89374	eval-mlogloss:0.89659

[I 2026-06-28 08:49:19,722] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96644	eval-mlogloss:0.95668

[I 2026-06-28 08:49:19,751] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09144	eval-mlogloss:1.09452
[1]	train-mlogloss:1.07565	eval-mlogloss:1.07767
[2]	train-mlogloss:1.06006	eval-mlogloss:1.06116
[3]	train-mlogloss:1.04853	eval-mlogloss:1.04767
[4]	train-mlogloss:1.03628	eval-mlogloss:1.03523
[5]	train-mlogloss:1.02139	eval-mlogloss:1.01974
[6]	train-mlogloss:1.01010	eval-mlogloss:1.00798
[7]	train-mlogloss:1.00255	eval-mlogloss:1.00214
[8]	train-mlogloss:0.98842	eval-mlogloss:0.98699
[9]	train-mlogloss:0.97747	eval-mlogloss:0.97593
[10]	train-mlogloss:0.96407	eval-mlogloss:0.96214
[11]	train-mlogloss:0.95218	eval-mlogloss:0.94949
[12]	train-mlogloss:0.94677	eval-mlogloss:0.94389
[13]	train-mlogloss:0.93363	eval-mlogloss:0.92963
[14]	train-mlogloss:0.92932	eval-mlogloss:0.92597
[15]	train-mlogloss:0.92169	eval-mlogloss:0.91877
[16]	train-mlogloss:0.91299	eval-mlogloss:0.90994
[17]	train-mlogloss:0.90323	eval-mlogloss:0.90085
[18]	train-mlogloss:0.89622	eval-mlogloss:0.89391
[19]	train-mlogloss:0.88910	eval-mlogloss:0.88703
[20]	train-mlogloss:0.87747	eval-mlogloss:0.87535
[21]	train-mlogloss:0.86886	eval-mlogloss:0.86586
[22]	train-mlogloss:0.86151	eval-mlogloss:0.85797
[23]	train-mlogloss:0.84980	eval-mlogloss:0.84536
[24]	train-mlogloss:0.84307	eval-mlogloss:0.83785
[25]	train-mlogloss:0.83494	eval-mlogloss:0.82901
[26]	train-mlogloss:0.82595	eval-mlogloss:0.81978
[27]	train-mlogloss:0.82310	eval-mlogloss:0.81737
[28]	train-mlogloss:0.81911	eval-mlogloss:0.81398
[29]	train-mlogloss:0.81042	eval-mlogloss:0.80439
[30]	train-mlogloss:0.80270	eval-mlogloss:0.79695
[31]	train-mlogloss:0.79962	eval-mlogloss:0.79494
[32]	train-mlogloss:0.79456	eval-mlogloss:0.78966
[33]	train-mlogloss:0.78934	eval-mlogloss:0.78360
[34]	train-mlogloss:0.78026	eval-mlogloss:0.77377
[35]	train-mlogloss:0.77466	eval-mlogloss:0.76791
[36]	train-mlogloss:0.77032	eval-mlogloss:0.76350
[37]	train-mlogloss:0.76364	eval-mlogloss:0.75670
[38]	train-mlogloss:0.75618	eval-mlogloss:0.74890
[39]	train-mlogloss:0.75028	eval-mlogloss:0.74336
[40]	train-mlogloss:0.74718	eval-mlogloss:0.74031
[41]	train-mlogloss:0.74033	eval-mlogloss:0.73261
[42]	train-mlogloss:0.73797	eval-mlogloss:0.73093
[43]	train-mlogloss:0.73141	eval-mlogloss:0.72377
[44]	train-mlogloss:0.72416	eval-mlogloss:0.71577
[45]	train-mlogloss:0.72025	eval-mlogloss:0.71135
[46]	train-mlogloss:0.71373	eval-mlogloss:0.70389
[47]	train-mlogloss:0.70903	eval-mlogloss:0.69916
[48]	train-mlogloss:0.70167	eval-mlogloss:0.69145
[49]	train-mlogloss:0.69460	eval-mlogloss:0.68401
[50]	train-mlogloss:0.68767	eval-mlogloss:0.67640
[51]	train-mlogloss:0.68333	eval-mlogloss:0.67223
[52]	train-mlogloss:0.67950	eval-mlogloss:0.66913
[53]	train-mlogloss:0.67151	eval-mlogloss:0.66011
[54]	train-mlogloss:0.66751	eval-mlogloss:0.65597
[55]	train-mlogloss:0.65942	eval-mlogloss:0.64771
[56]	train-mlogloss:0.65287	eval-mlogloss:0.64090
[57]	train-mlogloss:0.64524	eval-mlogloss:0.63237
[58]	train-mlogloss:0.64128	eval-mlogloss:0.62847
[59]	train-mlogloss:0.63926	eval-mlogloss:0.62597
[60]	train-mlogloss:0.63398	eval-mlogloss:0.62019
[61]	train-mlogloss:0.62958	eval-mlogloss:0.61599
[62]	train-mlogloss:0.62217	eval-mlogloss:0.60784
[63]	train-mlogloss:0.61831	eval-mlogloss:0.60362
[64]	train-mlogloss:0.61584	eval-mlogloss:0.60111
[65]	train-mlogloss:0.61165	eval-mlogloss:0.59653
[66]	train-mlogloss:0.60595	eval-mlogloss:0.59069
[67]	train-mlogloss:0.60153	eval-mlogloss:0.58626
[68]	train-mlogloss:0.59919	eval-mlogloss:0.58408
[69]	train-mlogloss:0.59274	eval-mlogloss:0.57703
[70]	train-mlogloss:0.58832	eval-mlogloss:0.57224
[71]	train-mlogloss:0.58130	eval-mlogloss:0.56477
[72]	train-mlogloss:0.57594	eval-mlogloss:0.55898
[73]	train-mlogloss:0.57186	eval-mlogloss:0.55467
[74]	train-mlogloss:0.56721	eval-mlogloss:0.54994
[75]	train-mlogloss:0.56132	eval-mlogloss:0.54297
[76]	train-mlogloss:0.55791	eval-mlogloss:0.53942
[77]	train-mlogloss:0.55509	eval-mlogloss:0.53722
[78]	train-mlogloss:0.55172	eval-mlogloss:0.53423
[79]	train-mlogloss:0.54890	eval-mlogloss:0.53190
[80]	train-mlogloss:0.54582	eval-mlogloss:0.52857
[81]	train-mlogloss:0.54075	eval-mlogloss:0.52325
[82]	train-mlogloss:0.53756	eval-mlogloss:0.52014
[83]	train-mlogloss:0.53310	eval-mlogloss:0.51495
[84]	train-mlogloss:0.52958	eval-mlogloss:0.51134
[85]	train-mlogloss:0.52513	eval-mlogloss:0.50669
[86]	train-mlogloss:0.52081	eval-mlogloss:0.50192
[87]	train-mlogloss:0.51629	eval-mlogloss:0.49720
[88]	train-mlogloss:0.51282	eval-mlogloss:0.49306
[89]	train-mlogloss:0.50822	eval-mlogloss:0.48846
[90]	train-mlogloss:0.50407	eval-mlogloss:0.48391
[91]	train-mlogloss:0.50099	eval-mlogloss:0.48067
[92]	train-mlogloss:0.49581	eval-mlogloss:0.47504
[93]	train-mlogloss:0.49409	eval-mlogloss:0.47347
[94]	train-mlogloss:0.48888	eval-mlogloss:0.46756
[95]	train-mlogloss:0.48449	eval-mlogloss:0.46249
[96]	train-mlogloss:0.47957	eval-mlogloss:0.45721
[97]	train-mlogloss:0.47696	eval-mlogloss:0.45467
[98]	train-mlogloss:0.47385	eval-mlogloss:0.45100
[99]	train-mlogloss:0.47270	eval-mlogloss:0.45026
[100]	train-mlogloss:0.46927	eval-mlogloss:0.44676
[101]	train-mlogloss:0.46614	eval-mlogloss:0.44322
[102]	train-mlogloss:0.46383	eval-mlogloss:0.44092
[103]	train-mlogloss:0.45879	eval-mlogloss:0.43547
[104]	train-mlogloss:0.45617	eval-mlogloss:0.43253
[105]	train-mlogloss:0.45382	eval-mlogloss:0.43006
[106]	train-mlogloss:0.45053	eval-mlogloss:0.42668
[107]	train-mlogloss:0.44569	eval-mlogloss:0.42117
[108]	train-mlogloss:0.44318	eval-mlogloss:0.41844
[109]	train-mlogloss:0.43868	eval-mlogloss:0.41333
[110]	train-mlogloss:0.43593	eval-mlogloss:0.40992
[111]	train-mlogloss:0.43250	eval-mlogloss:0.40614
[112]	train-mlogloss:0.42993	eval-mlogloss:0.40357
[113]	train-mlogloss:0.42534	eval-mlogloss:0.39825
[114]	train-mlogloss:0.42315	eval-mlogloss:0.39572
[115]	train-mlogloss:0.42071	eval-mlogloss:0.39299
[116]	train-mlogloss:0.41650	eval-mlogloss:0.38835
[117]	train-mlogloss:0.41329	eval-mlogloss:0.38506
[118]	train-mlogloss:0.41039	eval-mlogloss:0.38192
[119]	train-mlogloss:0.40811	eval-mlogloss:0.37943
[120]	train-mlogloss:0.40441	eval-mlogloss:0.37521
[121]	train-mlogloss:0.40098	eval-mlogloss:0.37175
[122]	train-mlogloss:0.39743	eval-mlogloss:0.36752
[123]	train-mlogloss:0.39426	eval-mlogloss:0.36384
[124]	train-mlogloss:0.39150	eval-mlogloss:0.36087
[125]	train-mlogloss:0.38876	eval-mlogloss:0.35769
[126]	train-mlogloss:0.38665	eval-mlogloss:0.35545
[127]	train-mlogloss:0.38471	eval-mlogloss:0.35329
[128]	train-mlogloss:0.38192	eval-mlogloss:0.35021
[129]	train-mlogloss:0.37977	eval-mlogloss:0.34793
[130]	train-mlogloss:0.37932	eval-mlogloss:0.34754
[131]	train-mlogloss:0.37583	eval-mlogloss:0.34323
[132]	train-mlogloss:0.37317	eval-mlogloss:0.34014
[133]	train-mlogloss:0.37091	eval-mlogloss:0.33762
[134]	train-mlogloss:0.36924	eval-mlogloss:0.33596
[135]	train-mlogloss:0.36643	eval-mlogloss:0.33266
[136]	train-mlogloss:0.36425	eval-mlogloss:0.33029
[137]	train-mlogloss:0.36084	eval-mlogloss:0.32665
[138]	train-mlogloss:0.35854	eval-mlogloss:0.32403
[139]	train-mlogloss:0.35680	eval-mlogloss:0.32255
[140]	train-mlogloss:0.35437	eval-mlogloss:0.31981
[141]	train-mlogloss:0.35201	eval-mlogloss:0.31727
[142]	train-mlogloss:0.34956	eval-mlogloss:0.31471
[143]	train-mlogloss:0.34637	eval-mlogloss:0.31133
[144]	train-mlogloss:0.34366	eval-mlogloss:0.30816
[145]	train-mlogloss:0.34161	eval-mlogloss:0.30561
[146]	train-mlogloss:0.34010	eval-mlogloss:0.30385
[147]	train-mlogloss:0.33844	eval-mlogloss:0.30189
[148]	train-mlogloss:0.33671	eval-mlogloss:0.29990
[149]	train-mlogloss:0.33607	eval-mlogloss:0.29966
[150]	train-mlogloss:0.33343	eval-mlogloss:0.29673
[151]	train-mlogloss:0.33140	eval-mlogloss:0.29446
[152]	train-mlogloss:0.33020	eval-mlogloss:0.29320
[153]	train-mlogloss:0.32859	eval-mlogloss:0.29153
[154]	train-mlogloss:0.32559	eval-mlogloss:0.28828
[155]	train-mlogloss:0.32382	eval-mlogloss:0.28623
[156]	train-mlogloss:0.32202	eval-mlogloss:0.28423
[157]	train-mlogloss:0.32051	eval-mlogloss:0.28255
[158]	train-mlogloss:0.31828	eval-mlogloss:0.28000
[159]	train-mlogloss:0.31696	eval-mlogloss:0.27871
[160]	train-mlogloss:0.31523	eval-mlogloss:0.27683
[161]	train-mlogloss:0.31261	eval-mlogloss:0.27429
[162]	train-mlogloss:0.31162	eval-mlogloss:0.27321
[163]	train-mlogloss:0.31070	eval-mlogloss:0.27239
[164]	train-mlogloss:0.31008	eval-mlogloss:0.27178
[165]	train-mlogloss:0.30899	eval-mlogloss:0.27055
[166]	train-mlogloss:0.30654	eval-mlogloss:0.26792
[167]	train-mlogloss:0.30409	eval-mlogloss:0.26509
[168]	train-mlogloss:0.30232	eval-mlogloss:0.26319
[169]	train-mlogloss:0.30122	eval-mlogloss:0.26210
[170]	train-mlogloss:0.30091	eval-mlogloss:0.26196
[171]	train-mlogloss:0.29942	eval-mlogloss:0.26036
[172]	train-mlogloss:0.29884	eval-mlogloss:0.25975
[173]	train-mlogloss:0.29801	eval-mlogloss:0.25893
[174]	train-mlogloss:0.29666	eval-mlogloss:0.25731
[175]	train-mlogloss:0.29578	eval-mlogloss:0.25647
[176]	train-mlogloss:0.29426	eval-mlogloss:0.25480
[177]	train-mlogloss:0.29359	eval-mlogloss:0.25397
[178]	train-mlogloss:0.29197	eval-mlogloss:0.25236
[179]	train-mlogloss:0.29142	eval-mlogloss:0.25179
[180]	train-mlogloss:0.28965	eval-mlogloss:0.24968
[181]	train-mlogloss:0.28786	eval-mlogloss:0.24774
[182]	train-mlogloss:0.28681	eval-mlogloss:0.24656
[183]	train-mlogloss:0.28627	eval-mlogloss:0.24631
[184]	train-mlogloss:0.28461	eval-mlogloss:0.24442
[185]	train-mlogloss:0.28315	eval-mlogloss:0.24293
[186]	train-mlogloss:0.28161	eval-mlogloss:0.24131
[187]	train-mlogloss:0.28049	eval-mlogloss:0.24009
[188]	train-mlogloss:0.27897	eval-mlogloss:0.23804
[189]	train-mlogloss:0.27690	eval-mlogloss:0.23567
[190]	train-mlogloss:0.27591	eval-mlogloss:0.23459
[191]	train-mlogloss:0.27477	eval-mlogloss:0.23337
[192]	train-mlogloss:0.27353	eval-mlogloss:0.23193
[193]	train-mlogloss:0.27234	eval-mlogloss:0.23057
[194]	train-mlogloss:0.27080	eval-mlogloss:0.22878
[195]	train-mlogloss:0.26887	eval-mlogloss:0.22656
[196]	train-mlogloss:0.26765	eval-mlogloss:0.22532
[197]	train-mlogloss:0.26587	eval-mlogloss:0.22330
[198]	train-mlogloss:0.26520	eval-mlogloss:0.22243
[199]	train-mlogloss:0.26438	eval-mlogloss:0.22172
[200]	train-mlogloss:0.26313	eval-mlogloss:0.22035
[201]	train-mlogloss:0.26229	eval-mlogloss:0.21934
[202]	train-mlogloss:0.26165	eval-mlogloss:0.21864
[203]	train-mlogloss:0.26023	eval-mlogloss:0.21722
[204]	train-mlogloss:0.25934	eval-mlogloss:0.21635
[205]	train-mlogloss:0.25888	eval-mlogloss:0.21572
[206]	train-mlogloss:0.25790	eval-mlogloss:0.21478
[207]	train-mlogloss:0.25702	eval-mlogloss:0.21384
[208]	train-mlogloss:0.25588	eval-mlogloss:0.21262
[209]	train-mlogloss:0.25425	eval-mlogloss:0.21077
[210]	train-mlogloss:0.25391	eval-mlogloss:0.21030
[211]	train-mlogloss:0.25329	eval-mlogloss:0.20982
[212]	train-mlogloss:0.25201	eval-mlogloss:0.20832
[213]	train-mlogloss:0.25085	eval-mlogloss:0.20698
[214]	train-mlogloss:0.24946	eval-mlogloss:0.20549
[215]	train-mlogloss:0.24788	eval-mlogloss:0.20362
[216]	train-mlogloss:0.24759	eval-mlogloss:0.20346
[217]	train-mlogloss:0.24599	eval-mlogloss:0.20152
[218]	train-mlogloss:0.24556	eval-mlogloss:0.20109
[219]	train-mlogloss:0.24376	eval-mlogloss:0.19905
[220]	train-mlogloss:0.24316	eval-mlogloss:0.19834
[221]	train-mlogloss:0.24254	eval-mlogloss:0.19763
[222]	train-mlogloss:0.24161	eval-mlogloss:0.19658
[223]	train-mlogloss:0.24096	eval-mlogloss:0.19579
[224]	train-mlogloss:0.23986	eval-mlogloss:0.19457
[225]	train-mlogloss:0.23973	eval-mlogloss:0.19439
[226]	train-mlogloss:0.23895	eval-mlogloss:0.19349
[227]	train-mlogloss:0.23872	eval-mlogloss:0.19332
[228]	train-mlogloss:0.23789	eval-mlogloss:0.19247
[229]	train-mlogloss:0.23695	eval-mlogloss:0.19143
[230]	train-mlogloss:0.23677	eval-mlogloss:0.19129
[231]	train-mlogloss:0.23603	eval-mlogloss:0.19049
[232]	train-mlogloss:0.23580	eval-mlogloss:0.19036
[233]	train-mlogloss:0.23495	eval-mlogloss:0.18937
[234]	train-mlogloss:0.23382	eval-mlogloss:0.18806
[235]	train-mlogloss:0.23313	eval-mlogloss:0.18720
[236]	train-mlogloss:0.23254	eval-mlogloss:0.18661
[237]	train-mlogloss:0.23168	eval-mlogloss:0.18566
[238]	train-mlogloss:0.23110	eval-mlogloss:0.18496
[239]	train-mlogloss:0.23075	eval-mlogloss:0.18464
[240]	train-mlogloss:0.22988	eval-mlogloss:0.18364
[241]	train-mlogloss:0.22943	eval-mlogloss:0.18316
[242]	train-mlogloss:0.22883	eval-mlogloss:0.18252
[243]	train-mlogloss:0.22849	eval-mlogloss:0.18204
[244]	train-mlogloss:0.22788	eval-mlogloss:0.18149
[245]	train-mlogloss:0.22733	eval-mlogloss:0.18089
[246]	train-mlogloss:0.22707	eval-mlogloss:0.18051
[247]	train-mlogloss:0.22681	eval-mlogloss:0.18019
[248]	train-mlogloss:0.22667	eval-mlogloss:0.18008
[249]	train-mlogloss:0.22607	eval-mlogloss:0.17926
[250]	train-mlogloss:0.22506	eval-mlogloss:0.17797
[251]	train-mlogloss:0.22441	eval-mlogloss:0.17720
[252]	train-mlogloss:0.22398	eval-mlogloss:0.17675
[253]	train-mlogloss:0.22362	eval-mlogloss:0.17633
[254]	train-mlogloss:0.22295	eval-mlogloss:0.17548
[255]	train-mlogloss:0.22263	eval-mlogloss:0.17542

[I 2026-06-28 08:49:20,663] Trial 30 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.09260	eval-mlogloss:1.09552
[1]	train-mlogloss:1.07942	eval-mlogloss:1.08145
[2]	train-mlogloss:1.06636	eval-mlogloss:1.06762
[3]	train-mlogloss:1.05660	eval-mlogloss:1.05620
[4]	train-mlogloss:1.04627	eval-mlogloss:1.04570
[5]	train-mlogloss:1.03368	eval-mlogloss:1.03262
[6]	train-mlogloss:1.02410	eval-mlogloss:1.02263
[7]	train-mlogloss:1.01745	eval-mlogloss:1.01724
[8]	train-mlogloss:1.00541	eval-mlogloss:1.00434
[9]	train-mlogloss:0.99599	eval-mlogloss:0.99479
[10]	train-mlogloss:0.98452	eval-mlogloss:0.98298
[11]	train-mlogloss:0.97432	eval-mlogloss:0.97215
[12]	train-mlogloss:0.96966	eval-mlogloss:0.96733
[13]	train-mlogloss:0.95832	eval-mlogloss:0.95504
[14]	train-mlogloss:0.95458	eval-mlogloss:0.95187
[15]	train-mlogloss:0.94796	eval-mlogloss:0.94563
[16]	train-mlogloss:0.94043	eval-mlogloss:0.93798
[17]	train-mlogloss:0.93192	eval-mlogloss:0.93005
[18]	train-mlogloss:0.92585	eval-mlogloss:0.92410
[19]	train-mlogloss:0.91989	eval-mlogloss:0.91806
[20]	train-mlogloss:0.90970	eval-mlogloss:0.90784
[21]	train-mlogloss:0.90220	eval-mlogloss:0.89955
[22]	train-mlogloss:0.89574	eval-mlogloss:0.89262
[23]	train-mlogloss:0.88543	eval-mlogloss:0.88155
[24]	train-mlogloss:0.87947	eval-mlogloss:0.87490
[25]	train-mlogloss:0.87226	eval-mlogloss:0.86706
[26]	train-mlogloss:0.86427	eval-mlogloss:0.85885
[27]	train-mlogloss:0.86172	eval-mlogloss:0.85670
[28]	train-mlogloss:0.85814	eval-mlogloss:0.85363
[29]	train-mlogloss:0.85043	eval-mlogloss:0.84516
[30]	train-mlogloss:0.84353	eval-mlogloss:0.83849
[31]	train-mlogloss:0.84076	eval-mlogloss:0.83667
[32]	train-mlogloss:0.83623	eval-mlogloss:0.83199
[33]	train-mlogloss:0.83151	eval-mlogloss:0.82654
[34]	train-mlogloss:0.82340	eval-mlogloss:0.81778
[35]	train-mlogloss:0.81826	eval-mlogloss:0.81229
[36]	train-mlogloss:0.81433	eval-mlogloss:0.80831
[37]	train-mlogloss:0.80830	eval-mlogloss:0.80218
[38]	train-mlogloss:0.80158	eval-mlogloss:0.79518
[39]	train-mlogloss:0.79624	eval-mlogloss:0.79021
[40]	train-mlogloss:0.79340	eval-mlogloss:0.78741
[41]	train-mlogloss:0.78718	eval-mlogloss:0.78043
[42]	train-mlogloss:0.78497	eval-mlogloss:0.77884
[43]	train-mlogloss:0.77901	eval-mlogloss:0.77242
[44]	train-mlogloss:0.77241	eval-mlogloss:0.76515
[45]	train-mlogloss:0.76881	eval-mlogloss:0.76108
[46]	train-mlogloss:0.76300	eval-mlogloss:0.75459
[47]	train-mlogloss:0.75865	eval-mlogloss:0.75021
[48]	train-mlogloss:0.75189	eval-mlogloss:0.74316
[49]	train-mlogloss:0.74538	eval-mlogloss:0.73633
[50]	train-mlogloss:0.73903	eval-mlogloss:0.72939
[51]	train-mlogloss:0.73504	eval-mlogloss:0.72558
[52]	train-mlogloss:0.73148	eval-mlogloss:0.72270
[53]	train-mlogloss:0.72415	eval-mlogloss:0.71445
[54]	train-mlogloss:0.72044	eval-mlogloss:0.71064
[55]	train-mlogloss:0.71297	eval-mlogloss:0.70304
[56]	train-mlogloss:0.70690	eval-mlogloss:0.69678
[57]	train-mlogloss:0.69983	eval-mlogloss:0.68891
[58]	train-mlogloss:0.69612	eval-mlogloss:0.68527
[59]	train-mlogloss:0.69417	eval-mlogloss:0.68292
[60]	train-mlogloss:0.68922	eval-mlogloss:0.67750
[61]	train-mlogloss:0.68507	eval-mlogloss:0.67353
[62]	train-mlogloss:0.67814	eval-mlogloss:0.66595
[63]	train-mlogloss:0.67451	eval-mlogloss:0.66199
[64]	train-mlogloss:0.67213	eval-mlogloss:0.65958
[65]	train-mlogloss:0.66815	eval-mlogloss:0.65531
[66]	train-mlogloss:0.66282	eval-mlogloss:0.64994
[67]	train-mlogloss:0.65850	eval-mlogloss:0.64577
[68]	train-mlogloss:0.65625	eval-mlogloss:0.64364
[69]	train-mlogloss:0.65013	eval-mlogloss:0.63694
[70]	train-mlogloss:0.64593	eval-mlogloss:0.63242
[71]	train-mlogloss:0.63931	eval-mlogloss:0.62541
[72]	train-mlogloss:0.63427	eval-mlogloss:0.62000
[73]	train-mlogloss:0.63037	eval-mlogloss:0.61592
[74]	train-mlogloss:0.62591	eval-mlogloss:0.61143
[75]	train-mlogloss:0.62032	eval-mlogloss:0.60485
[76]	train-mlogloss:0.61703	eval-mlogloss:0.60144
[77]	train-mlogloss:0.61429	eval-mlogloss:0.59928
[78]	train-mlogloss:0.61107	eval-mlogloss:0.59643
[79]	train-mlogloss:0.60829	eval-mlogloss:0.59406
[80]	train-mlogloss:0.60531	eval-mlogloss:0.59086
[81]	train-mlogloss:0.60045	eval-mlogloss:0.58580
[82]	train-mlogloss:0.59741	eval-mlogloss:0.58284
[83]	train-mlogloss:0.59313	eval-mlogloss:0.57787
[84]	train-mlogloss:0.58975	eval-mlogloss:0.57442
[85]	train-mlogloss:0.58545	eval-mlogloss:0.56991
[86]	train-mlogloss:0.58110	eval-mlogloss:0.56514
[87]	train-mlogloss:0.57673	eval-mlogloss:0.56060
[88]	train-mlogloss:0.57335	eval-mlogloss:0.55656
[89]	train-mlogloss:0.56888	eval-mlogloss:0.55209
[90]	train-mlogloss:0.56481	eval-mlogloss:0.54765
[91]	train-mlogloss:0.56176	eval-mlogloss:0.54450
[92]	train-mlogloss:0.55667	eval-mlogloss:0.53900
[93]	train-mlogloss:0.55490	eval-mlogloss:0.53735
[94]	train-mlogloss:0.54982	eval-mlogloss:0.53163
[95]	train-mlogloss:0.54550	eval-mlogloss:0.52669
[96]	train-mlogloss:0.54061	eval-mlogloss:0.52110
[97]	train-mlogloss:0.53800	eval-mlogloss:0.51853
[98]	train-mlogloss:0.53490	eval-mlogloss:0.51491
[99]	train-mlogloss:0.53369	eval-mlogloss:0.51413
[100]	train-mlogloss:0.53035	eval-mlogloss:0.51071
[101]	train-mlogloss:0.52726	eval-mlogloss:0.50721
[102]	train-mlogloss:0.52490	eval-mlogloss:0.50496
[103]	train-mlogloss:0.51993	eval-mlogloss:0.49962
[104]	train-mlogloss:0.51720	eval-mlogloss:0.49662
[105]	train-mlogloss:0.51482	eval-mlogloss:0.49401
[106]	train-mlogloss:0.51160	eval-mlogloss:0.49073
[107]	train-mlogloss:0.50682	eval-mlogloss:0.48534
[108]	train-mlogloss:0.50428	eval-mlogloss:0.48259
[109]	train-mlogloss:0.49980	eval-mlogloss:0.47754
[110]	train-mlogloss:0.49703	eval-mlogloss:0.47415
[111]	train-mlogloss:0.49361	eval-mlogloss:0.47034
[112]	train-mlogloss:0.49103	eval-mlogloss:0.46779
[113]	train-mlogloss:0.48646	eval-mlogloss:0.46255
[114]	train-mlogloss:0.48419	eval-mlogloss:0.45995
[115]	train-mlogloss:0.48170	eval-mlogloss:0.45716
[116]	train-mlogloss:0.47747	eval-mlogloss:0.45254
[117]	train-mlogloss:0.47422	eval-mlogloss:0.44928
[118]	train-mlogloss:0.47119	eval-mlogloss:0.44618
[119]	train-mlogloss:0.46886	eval-mlogloss:0.44366
[120]	train-mlogloss:0.46475	eval-mlogloss:0.43917
[121]	train-mlogloss:0.46120	eval-mlogloss:0.43540
[122]	train-mlogloss:0.45714	eval-mlogloss:0.43083
[123]	train-mlogloss:0.45394	eval-mlogloss:0.42716
[124]	train-mlogloss:0.45115	eval-mlogloss:0.42417
[125]	train-mlogloss:0.44832	eval-mlogloss:0.42086
[126]	train-mlogloss:0.44613	eval-mlogloss:0.41856
[127]	train-mlogloss:0.44411	eval-mlogloss:0.41635
[128]	train-mlogloss:0.44124	eval-mlogloss:0.41321
[129]	train-mlogloss:0.43905	eval-mlogloss:0.41089
[130]	train-mlogloss:0.43837	eval-mlogloss:0.41045
[131]	train-mlogloss:0.43453	eval-mlogloss:0.40573
[132]	train-mlogloss:0.43144	eval-mlogloss:0.40244
[133]	train-mlogloss:0.42895	eval-mlogloss:0.39961
[134]	train-mlogloss:0.42720	eval-mlogloss:0.39783
[135]	train-mlogloss:0.42428	eval-mlogloss:0.39450
[136]	train-mlogloss:0.42183	eval-mlogloss:0.39191
[137]	train-mlogloss:0.41831	eval-mlogloss:0.38819
[138]	train-mlogloss:0.41576	eval-mlogloss:0.38558
[139]	train-mlogloss:0.41398	eval-mlogloss:0.38402
[140]	train-mlogloss:0.41144	eval-mlogloss:0.38118
[141]	train-mlogloss:0.40902	eval-mlogloss:0.37858
[142]	train-mlogloss:0.40648	eval-mlogloss:0.37588
[143]	train-mlogloss:0.40302	eval-mlogloss:0.37230
[144]	train-mlogloss:0.40008	eval-mlogloss:0.36888
[145]	train-mlogloss:0.39790	eval-mlogloss:0.36613
[146]	train-mlogloss:0.39592	eval-mlogloss:0.36376
[147]	train-mlogloss:0.39368	eval-mlogloss:0.36140
[148]	train-mlogloss:0.39163	eval-mlogloss:0.35907
[149]	train-mlogloss:0.39094	eval-mlogloss:0.35878
[150]	train-mlogloss:0.38786	eval-mlogloss:0.35554
[151]	train-mlogloss:0.38572	eval-mlogloss:0.35316
[152]	train-mlogloss:0.38421	eval-mlogloss:0.35155
[153]	train-mlogloss:0.38240	eval-mlogloss:0.34999
[154]	train-mlogloss:0.37931	eval-mlogloss:0.34665
[155]	train-mlogloss:0.37707	eval-mlogloss:0.34423
[156]	train-mlogloss:0.37505	eval-mlogloss:0.34210
[157]	train-mlogloss:0.37345	eval-mlogloss:0.34016
[158]	train-mlogloss:0.37113	eval-mlogloss:0.33751
[159]	train-mlogloss:0.36961	eval-mlogloss:0.33584
[160]	train-mlogloss:0.36735	eval-mlogloss:0.33344
[161]	train-mlogloss:0.36457	eval-mlogloss:0.33074
[162]	train-mlogloss:0.36318	eval-mlogloss:0.32908
[163]	train-mlogloss:0.36181	eval-mlogloss:0.32763
[164]	train-mlogloss:0.36099	eval-mlogloss:0.32675
[165]	train-mlogloss:0.35961	eval-mlogloss:0.32523
[166]	train-mlogloss:0.35695	eval-mlogloss:0.32240
[167]	train-mlogloss:0.35438	eval-mlogloss:0.31940
[168]	train-mlogloss:0.35254	eval-mlogloss:0.31737
[169]	train-mlogloss:0.35139	eval-mlogloss:0.31621
[170]	train-mlogloss:0.35102	eval-mlogloss:0.31598
[171]	train-mlogloss:0.34924	eval-mlogloss:0.31405
[172]	train-mlogloss:0.34859	eval-mlogloss:0.31337
[173]	train-mlogloss:0.34758	eval-mlogloss:0.31226
[174]	train-mlogloss:0.34614	eval-mlogloss:0.31051
[175]	train-mlogloss:0.34522	eval-mlogloss:0.30961
[176]	train-mlogloss:0.34344	eval-mlogloss:0.30777
[177]	train-mlogloss:0.34268	eval-mlogloss:0.30687
[178]	train-mlogloss:0.34077	eval-mlogloss:0.30497
[179]	train-mlogloss:0.34015	eval-mlogloss:0.30434
[180]	train-mlogloss:0.33828	eval-mlogloss:0.30215
[181]	train-mlogloss:0.33637	eval-mlogloss:0.30008
[182]	train-mlogloss:0.33509	eval-mlogloss:0.29851
[183]	train-mlogloss:0.33445	eval-mlogloss:0.29824
[184]	train-mlogloss:0.33267	eval-mlogloss:0.29621
[185]	train-mlogloss:0.33091	eval-mlogloss:0.29460
[186]	train-mlogloss:0.32914	eval-mlogloss:0.29284
[187]	train-mlogloss:0.32763	eval-mlogloss:0.29132
[188]	train-mlogloss:0.32578	eval-mlogloss:0.28897
[189]	train-mlogloss:0.32356	eval-mlogloss:0.28658
[190]	train-mlogloss:0.32233	eval-mlogloss:0.28525
[191]	train-mlogloss:0.32104	eval-mlogloss:0.28378
[192]	train-mlogloss:0.31974	eval-mlogloss:0.28223
[193]	train-mlogloss:0.31833	eval-mlogloss:0.28061
[194]	train-mlogloss:0.31667	eval-mlogloss:0.27874
[195]	train-mlogloss:0.31450	eval-mlogloss:0.27624
[196]	train-mlogloss:0.31300	eval-mlogloss:0.27465
[197]	train-mlogloss:0.31069	eval-mlogloss:0.27196
[198]	train-mlogloss:0.30977	eval-mlogloss:0.27081
[199]	train-mlogloss:0.30864	eval-mlogloss:0.26979
[200]	train-mlogloss:0.30727	eval-mlogloss:0.26841
[201]	train-mlogloss:0.30629	eval-mlogloss:0.26726
[202]	train-mlogloss:0.30551	eval-mlogloss:0.26647
[203]	train-mlogloss:0.30390	eval-mlogloss:0.26491
[204]	train-mlogloss:0.30292	eval-mlogloss:0.26395
[205]	train-mlogloss:0.30216	eval-mlogloss:0.26311
[206]	train-mlogloss:0.30106	eval-mlogloss:0.26201
[207]	train-mlogloss:0.29985	eval-mlogloss:0.26063
[208]	train-mlogloss:0.29852	eval-mlogloss:0.25923
[209]	train-mlogloss:0.29657	eval-mlogloss:0.25694
[210]	train-mlogloss:0.29617	eval-mlogloss:0.25641
[211]	train-mlogloss:0.29541	eval-mlogloss:0.25579
[212]	train-mlogloss:0.29395	eval-mlogloss:0.25408
[213]	train-mlogloss:0.29227	eval-mlogloss:0.25222
[214]	train-mlogloss:0.29072	eval-mlogloss:0.25052
[215]	train-mlogloss:0.28893	eval-mlogloss:0.24841
[216]	train-mlogloss:0.28860	eval-mlogloss:0.24818
[217]	train-mlogloss:0.28681	eval-mlogloss:0.24604
[218]	train-mlogloss:0.28634	eval-mlogloss:0.24553
[219]	train-mlogloss:0.28438	eval-mlogloss:0.24339
[220]	train-mlogloss:0.28357	eval-mlogloss:0.24235
[221]	train-mlogloss:0.28278	eval-mlogloss:0.24146
[222]	train-mlogloss:0.28172	eval-mlogloss:0.24034
[223]	train-mlogloss:0.28099	eval-mlogloss:0.23948
[224]	train-mlogloss:0.27948	eval-mlogloss:0.23788
[225]	train-mlogloss:0.27907	eval-mlogloss:0.23726
[226]	train-mlogloss:0.27821	eval-mlogloss:0.23628
[227]	train-mlogloss:0.27760	eval-mlogloss:0.23567
[228]	train-mlogloss:0.27673	eval-mlogloss:0.23478
[229]	train-mlogloss:0.27568	eval-mlogloss:0.23371
[230]	train-mlogloss:0.27542	eval-mlogloss:0.23346
[231]	train-mlogloss:0.27422	eval-mlogloss:0.23199
[232]	train-mlogloss:0.27385	eval-mlogloss:0.23175
[233]	train-mlogloss:0.27285	eval-mlogloss:0.23054
[234]	train-mlogloss:0.27131	eval-mlogloss:0.22882
[235]	train-mlogloss:0.27001	eval-mlogloss:0.22714
[236]	train-mlogloss:0.26926	eval-mlogloss:0.22626
[237]	train-mlogloss:0.26813	eval-mlogloss:0.22502
[238]	train-mlogloss:0.26729	eval-mlogloss:0.22411
[239]	train-mlogloss:0.26627	eval-mlogloss:0.22308
[240]	train-mlogloss:0.26491	eval-mlogloss:0.22155
[241]	train-mlogloss:0.26420	eval-mlogloss:0.22108
[242]	train-mlogloss:0.26354	eval-mlogloss:0.22030
[243]	train-mlogloss:0.26299	eval-mlogloss:0.21970
[244]	train-mlogloss:0.26236	eval-mlogloss:0.21911
[245]	train-mlogloss:0.26157	eval-mlogloss:0.21830
[246]	train-mlogloss:0.26111	eval-mlogloss:0.21782
[247]	train-mlogloss:0.26082	eval-mlogloss:0.21747
[248]	train-mlogloss:0.26069	eval-mlogloss:0.21732
[249]	train-mlogloss:0.25971	eval-mlogloss:0.21612
[250]	train-mlogloss:0.25857	eval-mlogloss:0.21474
[251]	train-mlogloss:0.25774	eval-mlogloss:0.21388
[252]	train-mlogloss:0.25727	eval-mlogloss:0.21333
[253]	train-mlogloss:0.25660	eval-mlogloss:0.21273
[254]	train-mlogloss:0.25582	eval-mlogloss:0.21187
[255]	train-mlogloss:0.25527	eval-mlogloss:0.21145

[I 2026-06-28 08:49:21,852] Trial 31 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.08261	eval-mlogloss:1.08586
[1]	train-mlogloss:1.04607	eval-mlogloss:1.04663
[2]	train-mlogloss:1.01277	eval-mlogloss:1.01044
[3]	train-mlogloss:0.98687	eval-mlogloss:0.98036

[I 2026-06-28 08:49:21,899] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.01031	eval-mlogloss:1.02349

[I 2026-06-28 08:49:21,946] Trial 33 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08344	eval-mlogloss:1.08665
[1]	train-mlogloss:1.05063	eval-mlogloss:1.05088
[2]	train-mlogloss:1.02798	eval-mlogloss:1.02760
[3]	train-mlogloss:1.00612	eval-mlogloss:1.00162

[I 2026-06-28 08:49:22,399] Trial 34 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06678	eval-mlogloss:1.07207

[I 2026-06-28 08:49:22,436] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09262	eval-mlogloss:1.09509
[1]	train-mlogloss:1.07913	eval-mlogloss:1.08063
[2]	train-mlogloss:1.06612	eval-mlogloss:1.06631
[3]	train-mlogloss:1.05614	eval-mlogloss:1.05489
[4]	train-mlogloss:1.04565	eval-mlogloss:1.04447
[5]	train-mlogloss:1.03287	eval-mlogloss:1.03109
[6]	train-mlogloss:1.02303	eval-mlogloss:1.02070
[7]	train-mlogloss:1.01648	eval-mlogloss:1.01548
[8]	train-mlogloss:1.00411	eval-mlogloss:1.00225
[9]	train-mlogloss:0.99443	eval-mlogloss:0.99235
[10]	train-mlogloss:0.98294	eval-mlogloss:0.98069
[11]	train-mlogloss:0.97259	eval-mlogloss:0.96964
[12]	train-mlogloss:0.96826	eval-mlogloss:0.96489
[13]	train-mlogloss:0.95698	eval-mlogloss:0.95260
[14]	train-mlogloss:0.95314	eval-mlogloss:0.94923
[15]	train-mlogloss:0.94652	eval-mlogloss:0.94287

[I 2026-06-28 08:49:22,559] Trial 36 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.02880	eval-mlogloss:1.03688

[I 2026-06-28 08:49:22,693] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04914	eval-mlogloss:1.05268

[I 2026-06-28 08:49:22,735] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88414	eval-mlogloss:0.89177

[I 2026-06-28 08:49:22,772] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99475	eval-mlogloss:1.00132

[I 2026-06-28 08:49:22,803] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09153	eval-mlogloss:1.09440
[1]	train-mlogloss:1.07621	eval-mlogloss:1.07824
[2]	train-mlogloss:1.06132	eval-mlogloss:1.06183
[3]	train-mlogloss:1.04987	eval-mlogloss:1.05000
[4]	train-mlogloss:1.03775	eval-mlogloss:1.03814
[5]	train-mlogloss:1.02305	eval-mlogloss:1.02264
[6]	train-mlogloss:1.01237	eval-mlogloss:1.01135
[7]	train-mlogloss:1.00444	eval-mlogloss:1.00459
[8]	train-mlogloss:0.99072	eval-mlogloss:0.98975
[9]	train-mlogloss:0.97994	eval-mlogloss:0.97894
[10]	train-mlogloss:0.96712	eval-mlogloss:0.96598
[11]	train-mlogloss:0.95573	eval-mlogloss:0.95402
[12]	train-mlogloss:0.95010	eval-mlogloss:0.94858
[13]	train-mlogloss:0.93756	eval-mlogloss:0.93495
[14]	train-mlogloss:0.93324	eval-mlogloss:0.93125
[15]	train-mlogloss:0.92540	eval-mlogloss:0.92389

[I 2026-06-28 08:49:22,877] Trial 41 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.07669	eval-mlogloss:1.07909
[1]	train-mlogloss:1.04929	eval-mlogloss:1.04981
[2]	train-mlogloss:1.01999	eval-mlogloss:1.01864
[3]	train-mlogloss:0.99114	eval-mlogloss:0.98906

[I 2026-06-28 08:49:22,936] Trial 42 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03905	eval-mlogloss:1.03754

[I 2026-06-28 08:49:22,987] Trial 43 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08397	eval-mlogloss:1.08735
[1]	train-mlogloss:1.05246	eval-mlogloss:1.05383
[2]	train-mlogloss:1.02153	eval-mlogloss:1.02015
[3]	train-mlogloss:0.99890	eval-mlogloss:0.99565

[I 2026-06-28 08:49:23,048] Trial 44 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.87493	eval-mlogloss:0.86650

[I 2026-06-28 08:49:23,096] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03900	eval-mlogloss:1.04630

[I 2026-06-28 08:49:23,139] Trial 46 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07395	eval-mlogloss:1.07850

[I 2026-06-28 08:49:23,183] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07974	eval-mlogloss:1.08209
[1]	train-mlogloss:1.05398	eval-mlogloss:1.05518
[2]	train-mlogloss:1.02911	eval-mlogloss:1.02948
[3]	train-mlogloss:1.00468	eval-mlogloss:1.00440

[I 2026-06-28 08:49:23,232] Trial 48 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06688	eval-mlogloss:1.06739

[I 2026-06-28 08:49:23,272] Trial 49 pruned. Trial was pruned at iteration 1.

Best trial: {'lambda': 0.0003434360054112741, 'alpha': 1.557035917472026e-06, 'eta': 0.1568178961264044, 'gamma': 0.0025425644579019253, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6677265794176557, 'colsample_bytree': 0.541111550069141}
Best accuracy: 1.0

In [37]:
! pip install optuna-integration[xgboost]

Requirement already satisfied: optuna-integration[xgboost] in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)

In [38]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()