<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
#!pip install optuna
import pandas as pd
import numpy as np

import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [65]:
# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [66]:
df=pd.read_csv(url,names=columns)

In [67]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [68]:
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)
df.fillna(df.mean(), inplace=True)

In [69]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.00000,180.000000,32.9,0.171,63,0
764,2,122.0,70.0,27.00000,155.548223,36.8,0.340,27,0
765,5,121.0,72.0,23.00000,112.000000,26.2,0.245,30,0
766,1,126.0,60.0,29.15342,155.548223,30.1,0.349,47,1
767,1,93.0,70.0,31.00000,155.548223,30.4,0.315,23,0

In [70]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.00000,180.000000,32.9,0.171,63,0
764,2,122.0,70.0,27.00000,155.548223,36.8,0.340,27,0
765,5,121.0,72.0,23.00000,112.000000,26.2,0.245,30,0
766,1,126.0,60.0,29.15342,155.548223,30.1,0.349,47,1
767,1,93.0,70.0,31.00000,155.548223,30.4,0.315,23,0

In [71]:
X=df.drop('Outcome',axis=1)
y=df['Outcome']

In [72]:
X_train, X_test, y_train, y_test= train_test_split(X,y ,test_size=0.2, random_state=42)

In [73]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [74]:
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (614, 8)
Test set shape: (154, 8)

In [83]:
# Define the objective function
def objectiveFunction(trial):
  # Suggest values for the hyperparameters
  n_estimators=trial.suggest_int('n_estimators',50,200)
  max_depth=trial.suggest_int('max_depth',3,20)

   # Create the RandomForestClassifier with suggested hyperparameters

  model=RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth,random_state=42)

  # Perform 3-fold cross-validation and calculate accuracy

  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score  # Return the accuracy score for Optuna to maximize

In [85]:
# Create a study object and optimize the objective function
study=optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(objectiveFunction,n_trials=50)

[I 2025-12-19 12:33:25,213] A new study created in memory with name: no-name-469d916a-8bd3-45d4-b406-7f7a354a6c45
[I 2025-12-19 12:33:27,012] Trial 0 finished with value: 0.7784791965566714 and parameters: {'n_estimators': 174, 'max_depth': 5}. Best is trial 0 with value: 0.7784791965566714.
[I 2025-12-19 12:33:27,686] Trial 1 finished with value: 0.7670891120675912 and parameters: {'n_estimators': 70, 'max_depth': 5}. Best is trial 0 with value: 0.7784791965566714.
[I 2025-12-19 12:33:29,071] Trial 2 finished with value: 0.7540490993145226 and parameters: {'n_estimators': 164, 'max_depth': 3}. Best is trial 0 with value: 0.7784791965566714.
[I 2025-12-19 12:33:29,680] Trial 3 finished with value: 0.755706998246453 and parameters: {'n_estimators': 61, 'max_depth': 9}. Best is trial 0 with value: 0.7784791965566714.
[I 2025-12-19 12:33:31,104] Trial 4 finished with value: 0.780113183484776 and parameters: {'n_estimators': 140, 'max_depth': 14}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:32,240] Trial 5 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 92, 'max_depth': 6}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:32,965] Trial 6 finished with value: 0.7621871512832775 and parameters: {'n_estimators': 64, 'max_depth': 11}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:34,738] Trial 7 finished with value: 0.7719512195121951 and parameters: {'n_estimators': 154, 'max_depth': 5}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:36,237] Trial 8 finished with value: 0.7670970827355332 and parameters: {'n_estimators': 83, 'max_depth': 11}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:36,962] Trial 9 finished with value: 0.7670970827355332 and parameters: {'n_estimators': 63, 'max_depth': 20}. Best is trial 4 with value: 0.780113183484776.
[I 2025-12-19 12:33:37,777] Trial 10 finished with value: 0.7817471704128806 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 10 with value: 0.7817471704128806.
[I 2025-12-19 12:33:38,545] Trial 11 finished with value: 0.78012912482066 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 10 with value: 0.7817471704128806.
[I 2025-12-19 12:33:39,247] Trial 12 finished with value: 0.7785031085604973 and parameters: {'n_estimators': 113, 'max_depth': 17}. Best is trial 10 with value: 0.7817471704128806.
[I 2025-12-19 12:33:40,438] Trial 13 finished with value: 0.7752191933684043 and parameters: {'n_estimators': 195, 'max_depth': 16}. Best is trial 10 with value: 0.7817471704128806.
[I 2025-12-19 12:33:41,155] Trial 14 finished with value: 0.7784951378925554 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 10 with value: 0.7817471704128806.
[I 2025-12-19 12:33:41,961] Trial 15 finished with value: 0.7817631117487646 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:42,814] Trial 16 finished with value: 0.780121154152718 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:43,462] Trial 17 finished with value: 0.7736091184441256 and parameters: {'n_estimators': 102, 'max_depth': 14}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:44,334] Trial 18 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 138, 'max_depth': 15}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:45,463] Trial 19 finished with value: 0.7736011477761836 and parameters: {'n_estimators': 184, 'max_depth': 18}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:46,389] Trial 20 finished with value: 0.7654471544715448 and parameters: {'n_estimators': 153, 'max_depth': 9}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:47,206] Trial 21 finished with value: 0.78012912482066 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:48,185] Trial 22 finished with value: 0.7736170891120676 and parameters: {'n_estimators': 106, 'max_depth': 12}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:49,395] Trial 23 finished with value: 0.7817551410808226 and parameters: {'n_estimators': 131, 'max_depth': 16}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:50,302] Trial 24 finished with value: 0.7817471704128806 and parameters: {'n_estimators': 135, 'max_depth': 13}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:51,271] Trial 25 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 157, 'max_depth': 20}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:51,865] Trial 26 finished with value: 0.7768691216323927 and parameters: {'n_estimators': 93, 'max_depth': 16}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:52,671] Trial 27 finished with value: 0.7817551410808226 and parameters: {'n_estimators': 132, 'max_depth': 18}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:53,549] Trial 28 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 143, 'max_depth': 19}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:54,605] Trial 29 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 174, 'max_depth': 15}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:55,609] Trial 30 finished with value: 0.7735931771082417 and parameters: {'n_estimators': 167, 'max_depth': 9}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:56,466] Trial 31 finished with value: 0.7817551410808226 and parameters: {'n_estimators': 131, 'max_depth': 18}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:58,029] Trial 32 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 148, 'max_depth': 18}. Best is trial 15 with value: 0.7817631117487646.
[I 2025-12-19 12:33:59,364] Trial 33 finished with value: 0.7833811573409851 and parameters: {'n_estimators': 128, 'max_depth': 16}. Best is trial 33 with value: 0.7833811573409851.
[I 2025-12-19 12:34:01,220] Trial 34 finished with value: 0.7784951378925554 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 33 with value: 0.7833811573409851.
[I 2025-12-19 12:34:03,100] Trial 35 finished with value: 0.7866411605292524 and parameters: {'n_estimators': 118, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:04,853] Trial 36 finished with value: 0.7736170891120676 and parameters: {'n_estimators': 118, 'max_depth': 12}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:06,426] Trial 37 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 98, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:07,404] Trial 38 finished with value: 0.7752431053722302 and parameters: {'n_estimators': 81, 'max_depth': 10}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:09,211] Trial 39 finished with value: 0.7784871672246134 and parameters: {'n_estimators': 116, 'max_depth': 16}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:11,097] Trial 40 finished with value: 0.7850071736011478 and parameters: {'n_estimators': 144, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:12,004] Trial 41 finished with value: 0.7866331898613104 and parameters: {'n_estimators': 146, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:13,002] Trial 42 finished with value: 0.7833731866730432 and parameters: {'n_estimators': 148, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:14,451] Trial 43 finished with value: 0.7866331898613104 and parameters: {'n_estimators': 162, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:15,733] Trial 44 finished with value: 0.7670811413996493 and parameters: {'n_estimators': 163, 'max_depth': 7}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:16,799] Trial 45 finished with value: 0.7784712258887295 and parameters: {'n_estimators': 175, 'max_depth': 11}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:17,755] Trial 46 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 156, 'max_depth': 12}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:18,718] Trial 47 finished with value: 0.75242308305436 and parameters: {'n_estimators': 184, 'max_depth': 3}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:19,617] Trial 48 finished with value: 0.7784712258887295 and parameters: {'n_estimators': 147, 'max_depth': 10}. Best is trial 35 with value: 0.7866411605292524.
[I 2025-12-19 12:34:19,940] Trial 49 finished with value: 0.7833811573409851 and parameters: {'n_estimators': 50, 'max_depth': 13}. Best is trial 35 with value: 0.7866411605292524.

In [86]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7866411605292524
Best hyperparameters: {'n_estimators': 118, 'max_depth': 13}

In [90]:
# Train a RandomForestClassifier using the best hyperparameters from Optuna

best_model=RandomForestClassifier(**study.best_trial.params,random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

**Samplers in Optuna**

In [91]:
# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [93]:
study1 = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study1.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-12-19 13:06:17,810] A new study created in memory with name: no-name-3fd74018-131c-4eae-8e56-0660b549a8f1
[I 2025-12-19 13:06:20,712] Trial 0 finished with value: 0.75242308305436 and parameters: {'n_estimators': 122, 'max_depth': 3}. Best is trial 0 with value: 0.75242308305436.
[I 2025-12-19 13:06:23,622] Trial 1 finished with value: 0.7817551410808226 and parameters: {'n_estimators': 127, 'max_depth': 14}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:25,539] Trial 2 finished with value: 0.7768770923003347 and parameters: {'n_estimators': 63, 'max_depth': 13}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:27,592] Trial 3 finished with value: 0.7719910728519049 and parameters: {'n_estimators': 100, 'max_depth': 11}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:31,847] Trial 4 finished with value: 0.7719432488442531 and parameters: {'n_estimators': 162, 'max_depth': 6}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:32,934] Trial 5 finished with value: 0.7768452096285668 and parameters: {'n_estimators': 52, 'max_depth': 17}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:33,646] Trial 6 finished with value: 0.7736170891120676 and parameters: {'n_estimators': 63, 'max_depth': 7}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:35,136] Trial 7 finished with value: 0.7801052128168341 and parameters: {'n_estimators': 157, 'max_depth': 16}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:36,756] Trial 8 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 145, 'max_depth': 17}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:38,206] Trial 9 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 148, 'max_depth': 10}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:38,917] Trial 10 finished with value: 0.7670731707317073 and parameters: {'n_estimators': 61, 'max_depth': 5}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:39,587] Trial 11 finished with value: 0.7589430894308943 and parameters: {'n_estimators': 67, 'max_depth': 8}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:40,939] Trial 12 finished with value: 0.7524310537223019 and parameters: {'n_estimators': 117, 'max_depth': 3}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:43,963] Trial 13 finished with value: 0.7703411445879165 and parameters: {'n_estimators': 176, 'max_depth': 19}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:46,504] Trial 14 finished with value: 0.7768531802965088 and parameters: {'n_estimators': 198, 'max_depth': 9}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:47,185] Trial 15 finished with value: 0.7507970667941973 and parameters: {'n_estimators': 77, 'max_depth': 3}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:49,267] Trial 16 finished with value: 0.7735931771082417 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:50,512] Trial 17 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:51,297] Trial 18 finished with value: 0.7507970667941973 and parameters: {'n_estimators': 86, 'max_depth': 3}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:53,087] Trial 19 finished with value: 0.7703411445879165 and parameters: {'n_estimators': 176, 'max_depth': 19}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:54,376] Trial 20 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 145, 'max_depth': 20}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:54,913] Trial 21 finished with value: 0.7784951378925554 and parameters: {'n_estimators': 91, 'max_depth': 6}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:55,914] Trial 22 finished with value: 0.7768691216323927 and parameters: {'n_estimators': 104, 'max_depth': 13}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:56,473] Trial 23 finished with value: 0.7768770923003347 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:58,163] Trial 24 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 163, 'max_depth': 5}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:06:59,225] Trial 25 finished with value: 0.7768691216323927 and parameters: {'n_estimators': 108, 'max_depth': 6}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:01,271] Trial 26 finished with value: 0.7784871672246134 and parameters: {'n_estimators': 174, 'max_depth': 13}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:02,729] Trial 27 finished with value: 0.7687071576598119 and parameters: {'n_estimators': 55, 'max_depth': 20}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:04,707] Trial 28 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 111, 'max_depth': 10}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:06,258] Trial 29 finished with value: 0.7703491152558585 and parameters: {'n_estimators': 97, 'max_depth': 14}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:07,369] Trial 30 finished with value: 0.78012912482066 and parameters: {'n_estimators': 104, 'max_depth': 14}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:10,302] Trial 31 finished with value: 0.7670811413996493 and parameters: {'n_estimators': 167, 'max_depth': 7}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:12,218] Trial 32 finished with value: 0.7752191933684043 and parameters: {'n_estimators': 161, 'max_depth': 15}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:12,902] Trial 33 finished with value: 0.771983102183963 and parameters: {'n_estimators': 69, 'max_depth': 7}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:14,699] Trial 34 finished with value: 0.7784871672246134 and parameters: {'n_estimators': 183, 'max_depth': 12}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:16,716] Trial 35 finished with value: 0.7768850629682768 and parameters: {'n_estimators': 113, 'max_depth': 12}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:17,395] Trial 36 finished with value: 0.771975131516021 and parameters: {'n_estimators': 59, 'max_depth': 18}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:18,236] Trial 37 finished with value: 0.7752431053722302 and parameters: {'n_estimators': 84, 'max_depth': 13}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:19,190] Trial 38 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 95, 'max_depth': 13}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:20,747] Trial 39 finished with value: 0.7736011477761836 and parameters: {'n_estimators': 106, 'max_depth': 6}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:21,622] Trial 40 finished with value: 0.7687151283277539 and parameters: {'n_estimators': 66, 'max_depth': 5}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:22,676] Trial 41 finished with value: 0.7687151283277539 and parameters: {'n_estimators': 57, 'max_depth': 7}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:24,928] Trial 42 finished with value: 0.7491710505340348 and parameters: {'n_estimators': 191, 'max_depth': 3}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:26,304] Trial 43 finished with value: 0.7768452096285668 and parameters: {'n_estimators': 134, 'max_depth': 10}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:27,305] Trial 44 finished with value: 0.7768531802965088 and parameters: {'n_estimators': 106, 'max_depth': 10}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:28,200] Trial 45 finished with value: 0.7540490993145226 and parameters: {'n_estimators': 169, 'max_depth': 3}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:28,589] Trial 46 finished with value: 0.763845050215208 and parameters: {'n_estimators': 64, 'max_depth': 9}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:29,048] Trial 47 finished with value: 0.771975131516021 and parameters: {'n_estimators': 71, 'max_depth': 19}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:29,685] Trial 48 finished with value: 0.7670731707317073 and parameters: {'n_estimators': 115, 'max_depth': 5}. Best is trial 1 with value: 0.7817551410808226.
[I 2025-12-19 13:07:30,468] Trial 49 finished with value: 0.7752191933684043 and parameters: {'n_estimators': 137, 'max_depth': 6}. Best is trial 1 with value: 0.7817551410808226.

In [94]:

# Print the best result
print(f'Best trial accuracy: {study1.best_trial.value}')
print(f'Best hyperparameters: {study1.best_trial.params}')

Best trial accuracy: 0.7866411605292524
Best hyperparameters: {'n_estimators': 120, 'max_depth': 13}

In [95]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study1.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

**Grid Sampler**

In [96]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [97]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-12-19 13:10:27,952] A new study created in memory with name: no-name-32658a7c-eaf9-49d3-971d-e95636468986
[I 2025-12-19 13:10:29,360] Trial 0 finished with value: 0.7654391838036028 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7654391838036028.
[I 2025-12-19 13:10:32,039] Trial 1 finished with value: 0.7735772357723577 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 1 with value: 0.7735772357723577.
[I 2025-12-19 13:10:32,579] Trial 2 finished with value: 0.7687151283277539 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 1 with value: 0.7735772357723577.
[I 2025-12-19 13:10:33,645] Trial 3 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 3 with value: 0.7752351347042882.
[I 2025-12-19 13:10:34,692] Trial 4 finished with value: 0.7703491152558585 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 3 with value: 0.7752351347042882.
[I 2025-12-19 13:10:35,217] Trial 5 finished with value: 0.7817391997449387 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:36,160] Trial 6 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:37,123] Trial 7 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:38,071] Trial 8 finished with value: 0.7784791965566714 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:39,341] Trial 9 finished with value: 0.7784712258887295 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:40,600] Trial 10 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:41,902] Trial 11 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:43,608] Trial 12 finished with value: 0.7768452096285668 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:44,350] Trial 13 finished with value: 0.7703411445879165 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:45,549] Trial 14 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-12-19 13:10:46,080] Trial 15 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.

In [98]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Best trial accuracy: 0.7817391997449387
Best hyperparameters: {'n_estimators': 50, 'max_depth': 10}
Test Accuracy with best hyperparameters: 0.75

**Optuna Visualizations**

In [99]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [100]:
# 1. Optimization History
plot_optimization_history(study).show()

In [101]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [102]:
# 3. Slice Plot
plot_slice(study).show()

In [103]:
# 4. Contour Plot
plot_contour(study).show()

In [104]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

**Optimizing Multiple ML Models**

In [105]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [106]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [107]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-12-19 13:27:39,387] A new study created in memory with name: no-name-2f634b9c-94a5-453c-a915-cf8fe6439704
[I 2025-12-19 13:27:44,409] Trial 0 finished with value: 0.752415112386418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 232, 'learning_rate': 0.01209759020070973, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.752415112386418.
[I 2025-12-19 13:27:49,960] Trial 1 finished with value: 0.7687151283277539 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 265, 'learning_rate': 0.020266419166077427, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.7687151283277539.
[I 2025-12-19 13:27:50,787] Trial 2 finished with value: 0.7703172325840906 and parameters: {'classifier': 'RandomForest', 'n_estimators': 175, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7703172325840906.
[I 2025-12-19 13:27:52,100] Trial 3 finished with value: 0.7784632552207875 and parameters: {'classifier': 'RandomForest', 'n_estimators': 252, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:53,310] Trial 4 finished with value: 0.7735931771082417 and parameters: {'classifier': 'RandomForest', 'n_estimators': 233, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:54,345] Trial 5 finished with value: 0.7687071576598119 and parameters: {'classifier': 'RandomForest', 'n_estimators': 188, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:54,396] Trial 6 finished with value: 0.7312689303363622 and parameters: {'classifier': 'SVM', 'C': 18.75501918891064, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:55,486] Trial 7 finished with value: 0.7508209787980232 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 78, 'learning_rate': 0.08781117464206295, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:56,365] Trial 8 finished with value: 0.7686991869918699 and parameters: {'classifier': 'RandomForest', 'n_estimators': 151, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:59,278] Trial 9 finished with value: 0.7703252032520326 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:27:59,380] Trial 10 finished with value: 0.7670891120675912 and parameters: {'classifier': 'SVM', 'C': 0.16690542085912421, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:28:02,847] Trial 11 finished with value: 0.7752191933684043 and parameters: {'classifier': 'RandomForest', 'n_estimators': 244, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.7784632552207875.
[I 2025-12-19 13:28:04,950] Trial 12 finished with value: 0.7784871672246134 and parameters: {'classifier': 'RandomForest', 'n_estimators': 238, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:06,714] Trial 13 finished with value: 0.7784791965566714 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:08,193] Trial 14 finished with value: 0.7686991869918699 and parameters: {'classifier': 'RandomForest', 'n_estimators': 299, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:08,391] Trial 15 finished with value: 0.7019209309740155 and parameters: {'classifier': 'SVM', 'C': 81.54788110917407, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:09,268] Trial 16 finished with value: 0.7654471544715448 and parameters: {'classifier': 'RandomForest', 'n_estimators': 202, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:09,945] Trial 17 finished with value: 0.768683245655986 and parameters: {'classifier': 'RandomForest', 'n_estimators': 129, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:09,980] Trial 18 finished with value: 0.7686991869918699 and parameters: {'classifier': 'SVM', 'C': 0.5157079426702547, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:13,184] Trial 19 finished with value: 0.7605930176948829 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 273, 'learning_rate': 0.25100018968375015, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:14,800] Trial 20 finished with value: 0.7735852064402997 and parameters: {'classifier': 'RandomForest', 'n_estimators': 205, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:16,164] Trial 21 finished with value: 0.7752032520325204 and parameters: {'classifier': 'RandomForest', 'n_estimators': 264, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:17,602] Trial 22 finished with value: 0.7703252032520326 and parameters: {'classifier': 'RandomForest', 'n_estimators': 277, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:18,825] Trial 23 finished with value: 0.7703252032520326 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:19,948] Trial 24 finished with value: 0.7670731707317073 and parameters: {'classifier': 'RandomForest', 'n_estimators': 218, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:21,257] Trial 25 finished with value: 0.7752112227004623 and parameters: {'classifier': 'RandomForest', 'n_estimators': 249, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:22,936] Trial 26 finished with value: 0.7752431053722302 and parameters: {'classifier': 'RandomForest', 'n_estimators': 285, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:24,248] Trial 27 finished with value: 0.7703092619161486 and parameters: {'classifier': 'RandomForest', 'n_estimators': 254, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:25,322] Trial 28 finished with value: 0.7573091025027897 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 51, 'learning_rate': 0.054289240181922264, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:25,403] Trial 29 finished with value: 0.7686991869918699 and parameters: {'classifier': 'SVM', 'C': 2.6256827537932805, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:28,431] Trial 30 finished with value: 0.7540730113183485 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 153, 'learning_rate': 0.255557593664956, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:30,101] Trial 31 finished with value: 0.7752431053722302 and parameters: {'classifier': 'RandomForest', 'n_estimators': 285, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:32,756] Trial 32 finished with value: 0.7687151283277539 and parameters: {'classifier': 'RandomForest', 'n_estimators': 286, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:35,832] Trial 33 finished with value: 0.7687151283277539 and parameters: {'classifier': 'RandomForest', 'n_estimators': 298, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:39,100] Trial 34 finished with value: 0.771975131516021 and parameters: {'classifier': 'RandomForest', 'n_estimators': 261, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:41,448] Trial 35 finished with value: 0.7719512195121951 and parameters: {'classifier': 'RandomForest', 'n_estimators': 217, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:43,678] Trial 36 finished with value: 0.7752191933684043 and parameters: {'classifier': 'RandomForest', 'n_estimators': 274, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:45,720] Trial 37 finished with value: 0.7573409851745576 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 220, 'learning_rate': 0.043000790630544225, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:47,962] Trial 38 finished with value: 0.771967160848079 and parameters: {'classifier': 'RandomForest', 'n_estimators': 258, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:50,226] Trial 39 finished with value: 0.7670572293958234 and parameters: {'classifier': 'RandomForest', 'n_estimators': 283, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:52,270] Trial 40 finished with value: 0.7670970827355332 and parameters: {'classifier': 'RandomForest', 'n_estimators': 239, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:54,254] Trial 41 finished with value: 0.7736011477761836 and parameters: {'classifier': 'RandomForest', 'n_estimators': 289, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:56,782] Trial 42 finished with value: 0.7703491152558585 and parameters: {'classifier': 'RandomForest', 'n_estimators': 270, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:59,482] Trial 43 finished with value: 0.7703411445879165 and parameters: {'classifier': 'RandomForest', 'n_estimators': 285, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:28:59,558] Trial 44 finished with value: 0.7475689462776981 and parameters: {'classifier': 'SVM', 'C': 4.047992917610275, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:01,806] Trial 45 finished with value: 0.7686991869918699 and parameters: {'classifier': 'RandomForest', 'n_estimators': 228, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:05,143] Trial 46 finished with value: 0.7751873106966364 and parameters: {'classifier': 'RandomForest', 'n_estimators': 251, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:09,096] Trial 47 finished with value: 0.7719591901801371 and parameters: {'classifier': 'RandomForest', 'n_estimators': 299, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:17,552] Trial 48 finished with value: 0.7589829427706042 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 270, 'learning_rate': 0.1186337225277856, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:18,401] Trial 49 finished with value: 0.6986609277857484 and parameters: {'classifier': 'SVM', 'C': 90.51788968003386, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:20,558] Trial 50 finished with value: 0.7670731707317073 and parameters: {'classifier': 'RandomForest', 'n_estimators': 168, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.7784871672246134.
[I 2025-12-19 13:29:22,303] Trial 51 finished with value: 0.7817391997449387 and parameters: {'classifier': 'RandomForest', 'n_estimators': 246, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:22,898] Trial 52 finished with value: 0.7654312131356608 and parameters: {'classifier': 'RandomForest', 'n_estimators': 104, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:24,490] Trial 53 finished with value: 0.7768531802965088 and parameters: {'classifier': 'RandomForest', 'n_estimators': 287, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:25,586] Trial 54 finished with value: 0.7784871672246134 and parameters: {'classifier': 'RandomForest', 'n_estimators': 201, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:26,645] Trial 55 finished with value: 0.7752431053722302 and parameters: {'classifier': 'RandomForest', 'n_estimators': 191, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:27,781] Trial 56 finished with value: 0.7752112227004623 and parameters: {'classifier': 'RandomForest', 'n_estimators': 207, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:29,028] Trial 57 finished with value: 0.7752351347042882 and parameters: {'classifier': 'RandomForest', 'n_estimators': 228, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:30,365] Trial 58 finished with value: 0.7768452096285668 and parameters: {'classifier': 'RandomForest', 'n_estimators': 188, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:30,447] Trial 59 finished with value: 0.7573250438386737 and parameters: {'classifier': 'SVM', 'C': 0.12183590704968791, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:32,362] Trial 60 finished with value: 0.7784871672246134 and parameters: {'classifier': 'RandomForest', 'n_estimators': 239, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:33,730] Trial 61 finished with value: 0.7817391997449387 and parameters: {'classifier': 'RandomForest', 'n_estimators': 245, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:35,026] Trial 62 finished with value: 0.7784871672246134 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:36,350] Trial 63 finished with value: 0.780113183484776 and parameters: {'classifier': 'RandomForest', 'n_estimators': 240, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:37,675] Trial 64 finished with value: 0.7817391997449387 and parameters: {'classifier': 'RandomForest', 'n_estimators': 241, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:39,282] Trial 65 finished with value: 0.7752191933684043 and parameters: {'classifier': 'RandomForest', 'n_estimators': 245, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:40,516] Trial 66 finished with value: 0.771967160848079 and parameters: {'classifier': 'RandomForest', 'n_estimators': 226, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:41,647] Trial 67 finished with value: 0.7735852064402997 and parameters: {'classifier': 'RandomForest', 'n_estimators': 208, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:43,422] Trial 68 finished with value: 0.7752032520325204 and parameters: {'classifier': 'RandomForest', 'n_estimators': 243, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:50,050] Trial 69 finished with value: 0.744293001753547 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 216, 'learning_rate': 0.02460355081954542, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:51,403] Trial 70 finished with value: 0.7752112227004623 and parameters: {'classifier': 'RandomForest', 'n_estimators': 254, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.
[I 2025-12-19 13:29:52,724] Trial 71 finished with value: 0.7784871672246134 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 51 with value: 0.7817391997449387.

In [108]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'RandomForest', 'n_estimators': 246, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}
Best trial accuracy: 0.7817391997449387

In [109]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.752415,2025-12-19 13:27:39.391774,2025-12-19 13:27:44.409398,0 days 00:00:05.017624,NaN,NaN,GradientBoosting,NaN,NaN,0.012098,13.0,8.0,10.0,232.0,COMPLETE
1,1,0.768715,2025-12-19 13:27:44.414816,2025-12-19 13:27:49.960395,0 days 00:00:05.545579,NaN,NaN,GradientBoosting,NaN,NaN,0.020266,8.0,3.0,8.0,265.0,COMPLETE
2,2,0.770317,2025-12-19 13:27:49.961328,2025-12-19 13:27:50.786962,0 days 00:00:00.825634,NaN,False,RandomForest,NaN,NaN,NaN,10.0,8.0,6.0,175.0,COMPLETE
3,3,0.778463,2025-12-19 13:27:50.788000,2025-12-19 13:27:52.100050,0 days 00:00:01.312050,NaN,False,RandomForest,NaN,NaN,NaN,17.0,2.0,8.0,252.0,COMPLETE
4,4,0.773593,2025-12-19 13:27:52.101031,2025-12-19 13:27:53.309928,0 days 00:00:01.208897,NaN,False,RandomForest,NaN,NaN,NaN,13.0,3.0,5.0,233.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.770325,2025-12-19 13:30:27.935000,2025-12-19 13:30:29.369530,0 days 00:00:01.434530,NaN,False,RandomForest,NaN,NaN,NaN,20.0,2.0,7.0,276.0,COMPLETE
96,96,0.770317,2025-12-19 13:30:29.370493,2025-12-19 13:30:30.557227,0 days 00:00:01.186734,NaN,False,RandomForest,NaN,NaN,NaN,19.0,5.0,6.0,241.0,COMPLETE
97,97,0.775211,2025-12-19 13:30:30.558303,2025-12-19 13:30:31.913175,0 days 00:00:01.354872,NaN,False,RandomForest,NaN,NaN,NaN,18.0,2.0,8.0,257.0,COMPLETE
98,98,0.684051,2025-12-19 13:30:31.914284,2025-12-19 13:30:31.953564,0 days 00:00:00.039280,13.529949,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.741049,2025-12-19 13:30:31.954462,2025-12-19 13:30:38.748585,0 days 00:00:06.794123,NaN,NaN,GradientBoosting,NaN,NaN,0.011670,20.0,1.0,6.0,215.0,COMPLETE

In [110]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
RandomForest        79
GradientBoosting    11
SVM                 10
Name: count, dtype: int64

In [111]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.754810
RandomForest        0.773570
SVM                 0.735493
Name: value, dtype: float64

In [112]:
# 1. Optimization History
plot_optimization_history(study).show()

In [113]:
# 3. Slice Plot
plot_slice(study).show()

In [114]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [116]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.6.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.6.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.1.2)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.17.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.28.9)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.6.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 5.2 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.6.0

In [117]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()

[W 2025-12-19 13:32:12,604] Study instance does not contain trials.